### ISSUE TITLE
Provide the derivation of schemes for extremely high accuracy

### ISSUE THREAD

**Issue by AuroraDysis** [SciML/OrdinaryDiffEq.jl#1000]
`Feagin12` and `Feagin14` are the recommended methods for extremely high accuracy, but their coefficients only have 60 decimal digits. 60 decimal digits are usually not enough for this regime. For example, [256-bit octuple precision](https://en.wikipedia.org/wiki/Octuple-precision_floating-point_format) provides approximately 71 decimal digits.

Here are some maple worksheets on the derivation of Runge-Kutta schemes, including Feagin's Runge-Kutta scheme. 
[Peter Stone's Maple worksheets on the derivation of Runge-Kutta schemes](http://www.peterstone.name/Maplepgs/RKcoeff.html)

**Comment by ChrisRackauckas** [comment]
For ultra high accuracy like that, extrapolation methods might actually be a better idea since they are infinite order. They didn't exist when the previous recommendation was written.

**Comment by AuroraDysis** [comment]
After reading related papers in #312, I agree that the parallel extrapolation method might be more efficient than high order Runge-Kutta method, but it still needs some tests to prove.

**Comment by ChrisRackauckas** [comment]
We've had one benchmark where an extrapolation method has benchmarked as the best method for low tolerances: https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/pull/776#issuecomment-504292224 . More work on this benchmark can probably be done: https://benchmarks.juliadiffeq.org/html/NonStiffODE/linear_wpd.html . It would be nice if someone extended DiffEqBenchmarks a bit and added some benchmarks of very precise behavior. The energy precision benchmarks showcase some of this:

https://benchmarks.juliadiffeq.org/html/DynamicalODE/Henon-Heiles_energy_conservation_benchmark.html

https://benchmarks.juliadiffeq.org/html/DynamicalODE/Quadrupole_boson_Hamiltonian_energy_conservation_benchmark.html

**Comment by ChrisRackauckas** [comment]
Note that the extrapolation methods can multithread to do multiple stages at the same time, so it's likely to be fairly efficient when there's a lot of stages due to that reason as well, whereas most Runge-Kutta methods do not give that much parallelism.

**Comment by AuroraDysis** [comment]
It looks good. I'm interested in that because I usually need high precision solutions. I'll try and see if I can make some contributions.

**Comment by AuroraDysis** [comment]
@ChrisRackauckas I read `extrapolation_perform_step.jl` carefully and found it seems to be missing something like
```julia
if indices[2] <= indices[1]
  break
end
```
in loops of balance workload.
For example, in
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/9c1b4baa9965a8df91e39ff2d59a573b5fa5b9ab/src/perform_step/extrapolation_perform_step.jl#L1363-L1376
and
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/9c1b4baa9965a8df91e39ff2d59a573b5fa5b9ab/src/perform_step/extrapolation_perform_step.jl#L1174-L1188

**Comment by ChrisRackauckas** [comment]
That should be handled by the condition `0:(n_curr ÷ 2) `

**Comment by AuroraDysis** [comment]
I don't think it is handled. For example,
```julia
Threads.@threads for i in 0:(n_curr ÷ 2)
    indices = (i, n_curr - i)
    @info "test" indices
    for index in indices
        @info "test" index
        j_int_temp = 4 * subdividing_sequence[index + 1]
        dt_int_temp = dt / j_int_temp # Stepsize of the ith internal discretisation
        u_temp4 = uprev
        u_temp3 = u_temp4 + dt_int_temp * integrator.fsalfirst # Euler starting step
        for j in 2:j_int_temp
            T[index + 1] = u_temp4 + 2 * dt_int_temp * f(u_temp3, p, t + (j - 1) * dt_int_temp) # Explicit Midpoint rule
            u_temp4 = u_temp3
            u_temp3 = T[index + 1]
        end
    end
end
```
```
┌ Info: test
│   indices = (0, 4)
└ @ Main In[42]:77
┌ Info: test
│   index = 0
└ @ Main In[42]:79
┌ Info: test
│   index = 4
└ @ Main In[42]:79
┌ Info: test
│   indices = (1, 3)
└ @ Main In[42]:77
┌ Info: test
│   index = 1
└ @ Main In[42]:79
┌ Info: test
│   index = 3
└ @ Main In[42]:79
┌ Info: test
│   indices = (2, 2)
└ @ Main In[42]:77
┌ Info: test
│   index = 2
└ @ Main In[42]:79
┌ Info: test
│   index = 2
```

**Comment by ChrisRackauckas** [comment]
Oh indeed, I didn't think about that one. 

```julia
if indices[2] <= indices[1]
  break
end
```

isn't enough, since it does need to fill in the values for `2` at least once there. But yes, it's quite close, and this is a small efficiency issue to fix up.

**Comment by ChrisRackauckas** [comment]
The extrapolation methods are completed. See https://www.youtube.com/watch?v=tflagi32_rc. These will be the best for super low tolerances.
