### ISSUE TITLE
GPU Image Fails Tests

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/OrdinaryDiffEq.jl#1103]
@maleadt this GPU image seems to fail tests https://gitlab.com/juliadiffeq/OrdinaryDiffEq-jl/-/jobs/498508969 while it's an upstream call of the same test that passes with DiffEqBase.jl: https://gitlab.com/juliadiffeq/DiffEqBase-jl/-/jobs/485606671 . Do you know why these two Gitlab runner YAMLs would cause both to install seemingly correctly, but one passes and the other fails tests?

**Comment by maleadt** [comment]
Manifest differences, you are using GPUArrays 3.0 vs 2.0.

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/SciML/DiffEqBase.jl/commit/86f81ac7d90da04078456e5c365e9a01f27a1a1c . Odd that the new GPUArrays produces the wrong array size when multiplying a CuMatrix{Float64} with a CuVector{Float32} (gives a 3x1 CuMatrix), but that's somewhat a "user error" in our case.

**Comment by maleadt** [comment]
> Odd that the new GPUArrays produces the wrong array size when multiplying a CuMatrix{Float64} with a CuVector{Float32} (gives a 3x1 CuMatrix),

That seems wrong, could you elaborate? There's been some changes to the GPUArrays gemm fallback when CUBLAS is unavailable (by @haampie), so it's possible there's a difference between both.

**Comment by maleadt** [comment]
Ah OK this is https://github.com/JuliaGPU/CuArrays.jl/issues/673
