### ISSUE TITLE
Non-concrete array partition in-place interpolation fails due to element type calculation

### ISSUE THREAD

**Issue by ibulu** [SciML/OrdinaryDiffEq.jl#1238]
this works:
sol_univ = solve(prob_univ, Tsit5(),abstol = 1e-8, reltol = 1e-6);

this leads to an error:
sol_univ = solve(prob_univ, Tsit5(),abstol = 1e-8, reltol = 1e-6;saveat=tsteps);

MethodError: Cannot `convert` an object of type 
  ArrayPartition{Float64{},Tuple{Array{Float64{},1},Array{Float64,1},Array{Float64{},1},Array{Float64{},1},Array{Float64{},1},Array{Float64{},1},Array{Float64{},1},Array{Float64{},1},Array{Float64{},1},Array{Float64,1},Array{Float64{},1},Array{Float64{},1},Array{Float64{},1},Array{Float64{},1},Array{Float64{},1},Array{Float64{},1}}} to an object of type 
  ArrayPartition{Float64{},Tuple{Array{Float64{},1},Array{Float32,1},Array{Float64{},1},Array{Float64{},1},Array{Float64{},1},Array{Float64{},1},Array{Float64{},1},Array{Float64{},1},Array{Float64{},1},Array{Float32,1},Array{Float64{},1},Array{Float64{},1},Array{Float64{},1},Array{Float64{},1},Array{Float64{},1},Array{Float64{},1}}}
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T<:AbstractArray at abstractarray.jl:14
  convert(::Type{T}, !Matched::Factorization) where T<:AbstractArray at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/factorization.jl:55
  convert(::Type{T}, !Matched::T) where T at essentials.jl:171
  ...

**Comment by ibulu** [comment]
a minimal example to reproduce the issue:

```
using Unitful, RecursiveArrayTools, DiffEqBase, OrdinaryDiffEq
using LinearAlgebra

r0 = [1131.340, -2282.343, 6672.423]u"km"
v0 = [-5.64305, 4.30333, 2.42879]u"km/s"
Δt = 86400.0*365u"s"
μ = 398600.4418u"km^3/s^2"
rv0 = ArrayPartition(r0,v0)

function f(dy, y, μ, t)
    r = norm(y.x[1])
    dy.x[1] .= y.x[2]
    dy.x[2] .= -μ .* y.x[1] / r^3
end

prob = ODEProblem(f, rv0, (0.0u"s", Δt), μ)
sol = solve(prob, Vern8(), saveat=Δt/100.0)
```

**Comment by ChrisRackauckas** [comment]
Thanks for the MWE. That's very different than the reported issue haha.

**Comment by ibulu** [comment]
Aha! I guess I uncovered another issue while trying to create an MWE. Will try to put something together to reproduce the first issue too.

**Comment by ChrisRackauckas** [comment]
alright thanks
