### ISSUE TITLE
Possible bug in PI_stepsize_controller!

### ISSUE THREAD

**Issue by nathanaelbosch** [SciML/OrdinaryDiffEq.jl#1242]
While reading up on stepsize control I found some things in `PI_stepsize_controller!` that seemed surprising to me. I'm not very proficient on the matter so I could just misunderstand something, but I thought that there might actually be a bug. This should be easy to verify for someone that knows more about the details of OrdinaryDiffEq.jl.

The bits that surprised me:
- in [line 40](https://github.com/SciML/OrdinaryDiffEq.jl/blob/c3b05697ebecf24ef7c7f0d4db0ab116963b6851/src/integrators/controllers.jl#L40) `q11` gets assigned, but is not used before bein reassigned in [line 44](https://github.com/SciML/OrdinaryDiffEq.jl/blob/c3b05697ebecf24ef7c7f0d4db0ab116963b6851/src/integrators/controllers.jl#L40)
- On the other hand, I would assume that `integrator.qold`should be updated, similarly to what is done in `standard_stepsize_controller!` in [line 33](https://github.com/SciML/OrdinaryDiffEq.jl/blob/c3b05697ebecf24ef7c7f0d4db0ab116963b6851/src/integrators/controllers.jl#L33)

I could therefore imagine that [line 46](https://github.com/SciML/OrdinaryDiffEq.jl/blob/c3b05697ebecf24ef7c7f0d4db0ab116963b6851/src/integrators/controllers.jl#L46) should actually be something like
```julia
    integrator.qold = q11
```

**Comment by devmotion** [comment]
I'm not familiar with the stepsize algorithms but it seems for the PI controller `integrator.qold` is updated in https://github.com/SciML/OrdinaryDiffEq.jl/blob/c3b05697ebecf24ef7c7f0d4db0ab116963b6851/src/integrators/controllers.jl#L90 instead (in a different way). The `q11` in https://github.com/SciML/OrdinaryDiffEq.jl/blob/c3b05697ebecf24ef7c7f0d4db0ab116963b6851/src/integrators/controllers.jl#L40 might just be left from an earlier implementation and could just be removed, it seems.

**Comment by nathanaelbosch** [comment]
My bad, it seems I missed the update of `integrator.qold` in that file. Good to know that everything works as expected, and thank you for your fast reply!
