### ISSUE TITLE
Initial point issue for some interpolants (Rodas4)

### ISSUE THREAD

**Issue by moesphere** [SciML/OrdinaryDiffEq.jl#1266]
The `get_du` function does throw an error for certain customized interpolants, presumably an issue with the initial point and in the case of the Rodas4 family.

MWE:

```julia
using DifferentialEquations

function lorenz!(du,u,p,t)
 du[1] = 10.0*(u[2]-u[1])
 du[2] = u[1]*(28.0-u[3]) - u[2]
 du[3] = u[1]*u[2] - (8/3)*u[3]
end

u0 = [1.0;0.0;0.0]
tspan = (0.0,100.0)
prob = ODEProblem(lorenz!,u0,tspan)

integ1 = init(prob, Tsit5())
get_du(integ1) # works
integ2 = init(prob, Rodas4P())
get_du(integ2) # throws an error
```

See also [this discussion](https://discourse.julialang.org/t/callback-problem-with-differentialequations/46057/8) on julia discourse.

**Comment by MatFi** [comment]
fixed and can be closed.
