### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by ranocha** [SciML/OrdinaryDiffEq.jl#1284]
I noticed that SciML still uses travic-ci.org. travis-ci.org will be shut down at the end of the year, cf. https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom. Hence, everything should be migrated to travis-ci.com.

**Comment by ChrisRackauckas** [comment]
I thought we already migrated?

**Comment by ranocha** [comment]
Well, the badge in the README.md links to https://travis-ci.org/github/SciML/OrdinaryDiffEq.jl and tests are running there, e.g. the ones linked in https://github.com/SciML/OrdinaryDiffEq.jl/pull/1283.

**Comment by ranocha** [comment]
Superseded by #1305.
