### ISSUE TITLE
Stiffness detection & composite algorithm fail on CuArrays

### ISSUE THREAD

**Issue by PiotrSokol** [SciML/OrdinaryDiffEq.jl#1306]
Not specifying the solver for `DiffEqFlux.NeuralODE` makes the solver default to a CompositeAlgorithm with (Tsit5, Rosenbrock23). When testing the stiffness `derivative_utils.calc_J!` is invoked which in turns calls `LinearAlgebra.opnormInf` on a cuda array resulting in a `scalar getindex` error.

MWE
```
using DiffEqFlux, OrdinaryDiffEq, Flux
using CUDA
CUDA.allowscalar(false)
FT = Float32
u0  = CuArray(FT,randn(2,1))

nn_ode = NeuralODE(Dense(2,2, tanh) , (0.f0, 1.f0),
                   save_everystep = false,
                   reltol = 1e-3, abstol = 1e-3,
                   save_start = false) |> gpu

nn_ode(u0)
```

**Comment by ChrisRackauckas** [comment]
I fixed up the MWE and it seems to run fine?

```julia
using DiffEqFlux, OrdinaryDiffEq, Flux
using CUDA
CUDA.allowscalar(false)
FT = Float32
u0  = cu(randn(2,1))

nn_ode = NeuralODE(Dense(2,2, tanh) , (0.f0, 1.f0),
                   AutoTsit5(Rosenbrock23()),
                   save_everystep = false,
                   reltol = 1e-3, abstol = 1e-3,
                   save_start = false) |> gpu

nn_ode(u0,cu(nn_ode.p))
```

**Comment by PiotrSokol** [comment]
Sorry, was a doofus not testing it better before putting it up here. If memory serves, I was importing a different package from the ecosystem instead of `OrdinaryDiffEq` which resulted in this error.
