### ISSUE TITLE
Vector of StaticArrays inside ArrayPartition breaks the type of rate_prototype

### ISSUE THREAD

**Issue by Gregstrq** [SciML/OrdinaryDiffEq.jl#1308]
I have noticed, that if the state vector `u` is an `ArrayPartition` which contains `Vector` of `StaticArray`s, the computed type of the derivative vector `du` comes out wrong. I believe the problem resides in this line: https://github.com/SciML/OrdinaryDiffEq.jl/blob/69484227aa2b069d42f2c269339c84e34bbfa127/src/solve.jl#L184
Consider the following example:
```
using StaticArrays, RecursiveArrayTools

tType = Float64
u = ArrayPartition((zeros(5), zeros(SVector{3,Float64}, 5)))
typeof.(oneunit.(recursive_bottom_eltype.(u.x))./oneunit(tType))
```
gives you
>(Float64, Float64)

As a result, when `rate_prototype` is created, we get `Vector{Float64}` instead of `Vector{SVector{3,Float64}}` for the second part of `ArrayPartition`.

Since the line https://github.com/SciML/OrdinaryDiffEq.jl/blob/69484227aa2b069d42f2c269339c84e34bbfa127/src/solve.jl#L184 is supposed to correspond to the case without units, it actually looks completely out of place. The fix seems to be just to remove this line and calculate `rate_prototype` the same way it is done when `u` is not `ArrayPartition` in line https://github.com/SciML/OrdinaryDiffEq.jl/blob/69484227aa2b069d42f2c269339c84e34bbfa127/src/solve.jl#L182

**Comment by jdeldre** [comment]
I just was having the same problem. I actually suspect the error lies in the condition

https://github.com/SciML/OrdinaryDiffEq.jl/blob/69484227aa2b069d42f2c269339c84e34bbfa127/src/solve.jl#L181

It seems this should condition probably *not* be negated, since `recursivecopy` is a function created specifically to act on `ArrayPartition` types.
