### ISSUE TITLE
Typo in `__init` regarding DAEs: `u0` instead of `du0`

### ISSUE THREAD

**Issue by nathanaelbosch** [SciML/OrdinaryDiffEq.jl#1327]
The following line seems wrong: 
https://github.com/SciML/OrdinaryDiffEq.jl/blob/4bbb957203a5ff5f29017cb45aea1c96bf6dd54a/src/solve.jl#L138

I believe instead it should be:
```julia
      du = recursivecopy(prob.du0)
```

**Comment by ChrisRackauckas** [comment]
I think you are correct. I don't think it'll really matter since they should be similar, but it would be good to fix.

**Comment by ChrisRackauckas** [comment]
PR made, will merge when the tests pass.
