### ISSUE TITLE
Default value of `save_end`does not work anymore as expected

### ISSUE THREAD

**Issue by ranocha** [SciML/OrdinaryDiffEq.jl#1349]
Citing the [docs](https://diffeq.sciml.ai/v6.17/basics/common_solver_opts/#Output-Control)
> `save_end`: Denotes whether the final timepoint is forced to be saved, regardless of the other saving settings. Defaults to `true`.

We relied on this default value in our hyperbolic PDE solver framework [Trixi.jl](https://github.com/trixi-framework/Trixi.jl). The update https://github.com/SciML/OrdinaryDiffEq.jl/pull/1348 broke a lot of our tests, cf. https://github.com/trixi-framework/Trixi.jl/issues/453.

An MWE is
```julia
julia> using OrdinaryDiffEq # using v5.51.0

julia> ode = ODEProblem((u,p,t) -> u, 1.0, (0.0, 1.0))
ODEProblem with uType Float64 and tType Float64. In-place: false
timespan: (0.0, 1.0)
u0: 1.0

julia> sol = solve(ode, Tsit5(), save_everystep=false) # okay, as expected
retcode: Success
Interpolation: 1st order linear
t: 2-element Array{Float64,1}:
 0.0
 1.0
u: 2-element Array{Float64,1}:
 1.0
 2.718281708773342

julia> sol = solve(ode, Tsit5(), save_everystep=false, maxiters=3) # doesn't save the final solution anymore!
┌ Warning: Interrupted. Larger maxiters is needed.
└ @ SciMLBase ~/.julia/packages/SciMLBase/eghDQ/src/integrator_interface.jl:328
retcode: MaxIters
Interpolation: 1st order linear
t: 1-element Array{Float64,1}:
 0.0
u: 1-element Array{Float64,1}:
 1.0
```
We do have quite some regression tests where we set `maxiters` and want to check the final solution values. We also have other examples where we don't set `maxiters` but `terminate!` the integration using a callback; the final solution is not saved in all of these cases (but in some of them, which is a bit weird, I think).

Edit: To clarify, we have `isempty(saveat)` and `save_everystep==false`. Relying on the default value of `save_end`, this resulted in a solution array containing the initial data and the final solution and we rely on this behavior in a lot of setups and tests.

Is this something that should be fixed in OrdinaryDiffEq.jl or do we have to pass `save_end=true` everywhere?

**Comment by ChrisRackauckas** [comment]
That's a regression. Somehow, 0 of our tests found this. Indeed `save_end` should end up true and saving at the end and it's a bug that it isn't doing that.

**Comment by ranocha** [comment]
Thanks, that's good to know!

**Comment by ChrisRackauckas** [comment]
Yeah sorry about that. It seems like the early exiting saving behavior was a testing blind spot, and that's now fixed in https://github.com/SciML/OrdinaryDiffEq.jl/pull/1350.

**Comment by ranocha** [comment]
Thanks! A quick test of your branch in #1350 seems to work for us in Trixi.jl :+1:
