### ISSUE TITLE
Error when creating DAE problem in Turing @model

### ISSUE THREAD

**Issue by evrenmturan** [SciML/OrdinaryDiffEq.jl#1355]
When I create a DAEProblem within a Turing @model I get the error:

> ERROR: LoadError: TaskFailedException: MethodError: no method matching dae_fn!(::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Float64) Closest candidates are:   dae_fn!(::Any, ::Any, ::Any, ::Any, ::Any)

When I use the same line outside of the Turing @model it runs fine. Oddly enough I do not _always_ get this error.

**Comment by evrenmturan** [comment]
@ChrisRackauckas

**Comment by ChrisRackauckas** [comment]
Can you share code that leads to this?

**Comment by evrenmturan** [comment]
[MWE.txt](https://github.com/SciML/OrdinaryDiffEq.jl/files/6097034/MWE.txt)

**Comment by evrenmturan** [comment]
Remaking the problem with the below in @model also gives the same error:

>     prob_new = remake(prob1,p=p_new)
>     predicted = solve(prob_new,DABDF2(), saveat  = sol_true.t)
