### ISSUE TITLE
LoopVectorization issues

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/OrdinaryDiffEq.jl#1369]
https://github.com/SciML/SciMLBase.jl/runs/2305306322?check_suite_focus=true#step:6:507

@chriselrod SciMLBase downstream tests picked up a regression that looks to be due to changes in LoopVectorization.jl. Could you take a look at this?

**Comment by chriselrod** [comment]
Okay, I'll take a look shortly.

**Comment by chriselrod** [comment]
These issues look unrelated (unless I'm mistaken).

They're method errors, and VectorizationBase convert methods just happen to come up as closest candidates:
```julia
Cache Tests: Error During Test at /home/runner/.julia/packages/SafeTestsets/A83XK/src/SafeTestsets.jl:25
  Got exception outside of a @test
  LoadError: MethodError: Cannot `convert` an object of type Tuple{Bool} to an object of type Float64
  Closest candidates are:
    convert(::Type{T}, ::Union{VectorizationBase.AbstractSIMDVector{W, T}, VectorizationBase.VecUnroll{var"#s3", W, T, V} where {var"#s3", V<:VectorizationBase.AbstractSIMDVector{W, T}}} where {W, T}) where T<:Union{Bool, Float32, Float64, Int16, Int32, Int64, Int8, UInt16, UInt32, UInt64, UInt8, VectorizationBase.Bit} at /home/runner/.julia/packages/VectorizationBase/343do/src/base_defs.jl:136
    convert(::Type{T}, ::Base.TwicePrecision) where T<:Number at twiceprecision.jl:250
    convert(::Type{T}, ::AbstractChar) where T<:Number at char.jl:180
    ...
  Stacktrace:
    [1] setindex!(A::Vector{Float64}, x::Tuple{Bool}, i1::Int64)
      @ Base ./array.jl:839
    [2] _unsafe_copyto!(dest::Vector{Float64}, doffs::Int64, src::Vector{Tuple{Bool}}, soffs::Int64, n::Int64)
      @ Base ./array.jl:235
    [3] unsafe_copyto!
      @ ./array.jl:289 [inlined]
    [4] _copyto_impl!
      @ ./array.jl:313 [inlined]
    [5] copyto!
      @ ./array.jl:299 [inlined]
    [6] copyto!
      @ ./array.jl:325 [inlined]
    [7] copyto_axcheck!
      @ ./abstractarray.jl:1056 [inlined]
    [8] Vector{Float64}(x::Vector{Tuple{Bool}})
      @ Base ./array.jl:540
    [9] Array
      @ ./boot.jl:473 [inlined]
   [10] convert
      @ ./array.jl:532 [inlined]
   [11] adapt_storage
      @ ~/.julia/packages/Adapt/qRNxb/src/arrays.jl:10 [inlined]
   [12] adapt_structure
      @ ~/.julia/packages/Adapt/qRNxb/src/Adapt.jl:42 [inlined]
   [13] adapt
      @ ~/.julia/packages/Adapt/qRNxb/src/Adapt.jl:40 [inlined]
```
The other two examples are similar. 

All three cases show Adapt.jl in the stactrace.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/DiffEqFlux.jl/pull/523 it looks like Adapt 3.3 was a breaking release? I don't understand what downstream changes I'm supposed to make for it @maleadt

**Comment by maleadt** [comment]
I don't see how, it only contains https://github.com/JuliaGPU/Adapt.jl/pull/41 which adds an adapt rule for Array.

**Comment by ChrisRackauckas** [comment]
Agreed, I don't see how either. But at @chriselrod mentions, it all seems to stem from Adapt according to the stacktrace, and https://github.com/SciML/DiffEqFlux.jl/pull/523 shows that Adapt 3.2 works while 3.3 does not. Can't say I understand it, but the tests are pointing at it.

**Comment by chriselrod** [comment]
One of those new lines that was added,
```julia
# if an element type is specified, convert to it
Adapt.adapt_storage(::Type{<:Array{T}}, xs::AT) where {T, AT<:AbstractArray} =
  convert(Array{T}, xs)
```
Also shows up in the stack traces:
```julia
   [11] adapt_storage
      @ ~/.julia/packages/Adapt/qRNxb/src/arrays.jl:10 [inlined]
```

**Comment by maleadt** [comment]
FWIW, nobody really should have been calling `adapt(Array, ...)`, as that functionality was only accidentally supported by means of an incomplete definition in CUDA.jl (which has been removed in https://github.com/JuliaGPU/CUDA.jl/commit/17ed1428ce0d772b96c597a3aa29f03b4b34ec2b). The proper definitions, added in the Adapt PR mentioned above, now also support converting to different element types, as long as Array's convert methods support that. Such a mismatch is probably what's causing the issue here:

```julia
julia> adapt(Array{Float64}, [(true,)])
ERROR: MethodError: Cannot `convert` an object of type Tuple{Bool} to an object of type Float64
```

But that seems like a pretty iffy call in the first place.

**Comment by ChrisRackauckas** [comment]
Why would nobody call `adapt(Array, ...)`? I don't know how I would otherwise change say a Tridiagonal of CuArrays to a Tridiagonal of Arrays. I assumed that's what the package was for: doing those kinds of conversions to and from the GPU.

**Comment by maleadt** [comment]
> I assumed that's what the package was for: doing those kinds of conversions to and from the GPU.

Adapt is a package that provides tools for doing that kind of conversion, without defining the conversions themselves. So up until Adapt v3.3 there wasn't a rule for what `adapt(Array, ...)` did, that actually came from CUDA.jl. I've now removed that (incomplete) definition from CUDA.jl and provided a proper one in Adapt.jl (supporting conversions to different element types, which is what is tripping up existing code here).

**Comment by ChrisRackauckas** [comment]
So is the issue that CUDA.jl and Adapt.jl need to be updated at the same time?

**Comment by maleadt** [comment]
No, the problem is that the new definition in Adapt.jl honors the element type passed in, so `adapt(Array{Float32}, [(true,)])` now fails because `convert(Array{Float32}, [(true,)])` is an error. The old definition in CUDA.jl ignored the element type and just did `convert(Array, [(true,)])`. Since it's a little nonsensical to try and convert an array of tuples of bools to an array of floats, this seems like a user error, but as I said it's technically breaking that Adapt.jl now defines a conversion that's more restrictive than the old one in CUDA.jl (which was never intended to be used by code outside of CUDA.jl).

**Comment by ChrisRackauckas** [comment]
I think I see what you mean. We need to use the parameterless_type:

```julia
Base.@pure __parameterless_type(T) = Base.typename(T).wrapper
parameterless_type(x) = parameterless_type(typeof(x))
parameterless_type(x::Type) = __parameterless_type(x)
```

**Comment by maleadt** [comment]
Ah you're deriving the type from a value. Yeah, not a pretty thing (does that get inferred?) but from Adapt.jl's point of view it seems like the logical thing to do.

**Comment by ChrisRackauckas** [comment]
Yeah it's inferred fine because of the `@pure`. Alright, that seems like a change we have to be aware of and that's the fix. Thanks @maleadt !
