### ISSUE TITLE
PID step size controllers (and maybe even more?)

### ISSUE THREAD

**Issue by ranocha** [SciML/OrdinaryDiffEq.jl#1379]
As far as I understand, OrdinaryDiffEq uses PI controllers (with parameters `beta1, beta2`). Some algorithms seem to work best with PID controllers (adding a parameter `beta3` to the mix), as demonstrated in our [recent preprint](http://arxiv.org/abs/2104.06836). It would be great if PID controllers could be added as well. 

Talking about this, could it make sense to restructure the [controllers](https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/src/integrators/controllers.jl) by wrapping controllers in `struct`s and dispatch to distinguish different controllers? For example, the most general controller used in practice I know are the ones based of [Söderlind based on digital signal processing](https://dl.acm.org/doi/10.1145/641876.641877), which come with 5 parameters `alpha2, alpha3, beta1, beta2, beta3` and are [implemented in PETSc](https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/TS/TSADAPTDSP.html).

**Comment by ChrisRackauckas** [comment]
Yes, it would be good to add it, and have more ways of swapping controllers. Right now it's only swappable in certain algorithms.
