### ISSUE TITLE
Velocity Verlet integrator calculates the acceleration twice at each time step

### ISSUE THREAD

**Issue by jgreener64** [SciML/OrdinaryDiffEq.jl#1387]
I think the current `VelocityVerlet` implementation calculates the acceleration twice per time step:

```julia
using DifferentialEquations

accel_counter = 0

function acceleration!(accels, vels, coords, p, t)
    global accel_counter += 1
    accels .= zero(coords)
end

tspan = (0.0, 100.0)
prob = SecondOrderODEProblem(acceleration!, rand(100), rand(100), tspan)
sol = solve(prob, VelocityVerlet(), dt=1.0)

println(accel_counter)
```
```
201
```

There are only 100 steps here. Looking at https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/src/perform_step/symplectic_perform_step.jl#L192-L196 it seems that the current and next time step accelerations are calculated, but as shown in https://en.wikipedia.org/wiki/Verlet_integration#Velocity_Verlet you can store the last time step acceleration and use it again. This is a good idea, since the acceleration calculation is expensive.

This is on v5.52.2 of OrdinaryDiffEq.jl. I may have misunderstood something, it's my first time looking properly at the SciML code base (it's a fun adventure!).

**Comment by YingboMa** [comment]
Indeed it can reuse the acceleration calculation. I think you can access that via `integrator.fsallast.k[2]`. Do you want to make a PR?

**Comment by ChrisRackauckas** [comment]
Yeah, it just needs to use the FSAL value.

**Comment by jgreener64** [comment]
Great, I can look at making a PR.
