### ISSUE TITLE
Timing goes up for reiniting and resolving an integrator

### ISSUE THREAD

**Issue by tomaklutfu** [SciML/OrdinaryDiffEq.jl#1394]
Here MWE,
```julia
using OrdinaryDiffEq
using StaticArrays
using BenchmarkTools

f(u, p, t) = -u
u0 = SVector((0.0, 10.0, 0.0, 0.0))
prb = ODEProblem(f, u0, (0, 2.0))
integ = init(prb, Tsit5(), reltol=1e-6, abstol=1e-6, save_on=false);

for i = 1:10
  @btime begin
    reinit!(integ, u0)
    solve!(integ)
  end
end
```
I get
```julia
julia> include("../bug.jl")
  43.540 μs (11 allocations: 1.58 KiB)
  70.581 μs (11 allocations: 1.58 KiB)
  85.288 μs (11 allocations: 1.58 KiB)
  99.084 μs (11 allocations: 1.58 KiB)
  114.825 μs (11 allocations: 1.58 KiB)
  132.032 μs (11 allocations: 1.58 KiB)
  146.151 μs (11 allocations: 1.58 KiB)
  164.674 μs (11 allocations: 1.58 KiB)
  188.027 μs (11 allocations: 1.58 KiB)
  207.905 μs (11 allocations: 1.58 KiB)
```
As you see timings linearly increasing each time I resolve diff equation or `@btime` is at odds. Using regular arrays, i see the same trend too.

**Comment by YingboMa** [comment]
This is probably some Julia internal things, since the allocation doesn't really go up or anything.

**Comment by ChrisRackauckas** [comment]
No, the starting `dt` will have changed because `reinit` doesn't by default change dt again. Add the keyword argument `reset_dt=true` to `reinit!`

**Comment by tomaklutfu** [comment]
Originally, I had `reset_dt=true` but it does not make difference. With it
```julia
julia> include("../bug.jl")
  43.892 μs (12 allocations: 1.62 KiB)
  75.748 μs (12 allocations: 1.62 KiB)
  92.873 μs (12 allocations: 1.62 KiB)
  108.659 μs (12 allocations: 1.62 KiB)
  125.687 μs (12 allocations: 1.62 KiB)
  140.276 μs (12 allocations: 1.62 KiB)
  155.732 μs (12 allocations: 1.62 KiB)
  174.026 μs (12 allocations: 1.62 KiB)
  196.482 μs (12 allocations: 1.62 KiB)
  208.682 μs (12 allocations: 1.62 KiB)
```

**Comment by ChrisRackauckas** [comment]
what about with `erase_sol=true`? This is rather interesting.

**Comment by tomaklutfu** [comment]
No luck, the trend is the same though timings are lower
```julia
julia> include("../bug.jl")
  37.861 μs (12 allocations: 1.62 KiB)
  61.989 μs (12 allocations: 1.62 KiB)
  78.345 μs (12 allocations: 1.62 KiB)
  92.635 μs (12 allocations: 1.62 KiB)
  108.190 μs (12 allocations: 1.62 KiB)
  128.669 μs (12 allocations: 1.62 KiB)
  143.693 μs (12 allocations: 1.62 KiB)
  156.617 μs (12 allocations: 1.62 KiB)
  172.916 μs (12 allocations: 1.62 KiB)
  187.853 μs (12 allocations: 1.62 KiB)
```

**Comment by tomaklutfu** [comment]
Profiling directs to these lines
https://github.com/SciML/OrdinaryDiffEq.jl/blob/a401b8da41701722fdde79daf12661ceca4582c2/src/integrators/integrator_utils.jl#L120-L134
especially line 125 where `resize!` happens.

**Comment by tomaklutfu** [comment]
@YingboMa @ChrisRackauckas It seems `saveitr_dense` goes up every time with `solve!` called and then the `sol.k` grows unnecessarily. I think it should be `saveiter` instead.

**Comment by ChrisRackauckas** [comment]
If `dense==false` then `sol.k` is length 0, so you don't want that to be `saveiter`. But you do want to reset it in `init!`, which seems like it currently isn't being done. Add:

https://github.com/SciML/OrdinaryDiffEq.jl/blob/14bd5885de76cadfdebbae6d7ee5346efb765f91/src/integrators/integrator_interface.jl#L279-L296

a reset of `saveiter_dense` and see if that does it.

**Comment by tomaklutfu** [comment]
I can confirm adding this line after line 294 solves problem.
```julia
  integrator.saveiter_dense = resize_start
```
solves problem. If it is what you want I can make a pull request.

**Comment by tomaklutfu** [comment]
I don't know if something is catchy but there is 20x speed up after that. :smile:
