### ISSUE TITLE
Error combining BigFloats with callbacks

### ISSUE THREAD

**Issue by atiyo** [SciML/OrdinaryDiffEq.jl#1400]
I'm encountering some problems when callbacks are triggered when my system state is a `BigFloat`.

Example:

```julia
using OrdinaryDiffEq

f(u,p,t) = BigFloat(1.01)*u
u0 = BigFloat(1/2)
tspan = (0.0,1.0)

condition(u,t,integrator) = u - BigFloat(1.0)
cb = ContinuousCallback(condition, terminate!)

prob = ODEProblem(f,u0,tspan, callback=cb)
sol = solve(prob, Tsit5())
```

throws
```
ERROR: MethodError: no method matching recursivecopy!(::BigFloat, ::BigFloat)
```

If `condition` is never met (e.g. if `condition(u,t,integrator) = u - BigFloat(100.0))` above), everything works as expected.

If `condition` returns a `Float64` instead of a `BigFloat` (e.g. if `condition(u,t,integrator) = Float64(u) - 1.0` above), the error still occurrs.

Thanks for any help. Also, thanks for building out and maintaining this ecosystem.

**Comment by ChrisRackauckas** [comment]
Fixed by:

```julia
using ArrayInterface
ArrayInterface.ismutable(::Type{BigFloat}) = false
```

and thus https://github.com/JuliaArrays/ArrayInterface.jl/pull/150
