### ISSUE TITLE
Low-storage RK solvers test failure

### ISSUE THREAD

**Issue by YingboMa** [SciML/OrdinaryDiffEq.jl#1412]
![image](https://user-images.githubusercontent.com/17304743/119234919-157e7280-bafe-11eb-8c5d-c74f023c2122.png)

Because of the CI short-circuiting, tests were never run on those newly added solvers. When I checkout the `v5.54.0` tag locally, the tests fail. I think those solvers are merged with tests ever passing.

@ranocha could you fix those test failures?

CC: @ChrisRackauckas

**Comment by ranocha** [comment]
I will have a look
