### ISSUE TITLE
QNDF Event Handling

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/OrdinaryDiffEq.jl#1434]
QNDF is probably not safe for event handling? 

@YingboMa @JunpengGao233

**Comment by JunpengGao233** [comment]
Oh, I actually do not check this part. I will do this ASAP.

**Comment by ChrisRackauckas** [comment]
Fixed in https://github.com/SciML/OrdinaryDiffEq.jl/pull/1438
