### ISSUE TITLE
Change signature of stage limiters

### ISSUE THREAD

**Issue by ranocha** [SciML/OrdinaryDiffEq.jl#1444]
Right now, some methods support stage callback/limiters, e.g. SSP methods Right now, we have `stage_limiter!` for SSPRK methods and in-place problems: 
https://github.com/SciML/OrdinaryDiffEq.jl/blob/0c2048a502101647ac35faabd80da8a5645beac7/src/perform_step/ssprk_perform_step.jl#L43
We would like to use this feature more often in our hyperbolic PDE framework [Trixi.jl](https://github.com/trixi-framework/Trixi.jl). However, we noticed that we need additional information such as the current time step for some applications. Would it be possible to change the signature from
```julia
stage_limiter!(u, f, p, t) 
```
to something like
```julia
stage_limiter!(u, integrator, p, t) 
```
including the `integrator`? Alternatively, we could unify the signature with callbacks, i.e. just use
```julia
stage_limiter!(integrator) 
```
since this will have all of the information.

This would be a breaking change, but I honestly don't know whether anybody except us uses this feature :sweat_smile:  

Xref https://github.com/SciML/OrdinaryDiffEq.jl/issues/1292

**Comment by ChrisRackauckas** [comment]
Yeah it's breaking, but just go for it. If we want stage limiters to get generalized, maybe it needs to be `stage_limiter!(stageu, integrator, p, t)` since that may not necessarily be the same as `integrator.u`? I am trying to think of a case but in theory I guess we can make that cache always `u`, even though we don't right now.

**Comment by ranocha** [comment]
Thanks! `stage_limiter!(current_stage_u_just_computed, integrator, p, t)` sounds good to me. I will prepare something

**Comment by ChrisRackauckas** [comment]
Yeah, `t` is also needed since it should be the `t` at the stage, right? `tprev + dt * c`?

**Comment by ranocha** [comment]
Yes, exactly

**Comment by sloede** [comment]
Just as a side note: We would like to potentially use this feature (callbacks once per stage) for more than just limiting, thus the next time there's a breaking change here, it might make sense to introduce a more general name than "limiter".
