### ISSUE TITLE
Is there RKF algorithm implementation?

### ISSUE THREAD

**Issue by zhaofeng-shu33** [SciML/OrdinaryDiffEq.jl#1449]
After reading the full list of method at https://diffeq.sciml.ai/latest/solvers/ode_solve/#Full-List-of-Methods .
It seems to contain no RKF algorithm in this package. Does the maintainer have any plan to implement this or allow PR?

RKF: https://en.wikipedia.org/wiki/Runge%E2%80%93Kutta%E2%80%93Fehlberg_method

**Comment by ChrisRackauckas** [comment]
There is through `ExplicitTableau(constructRKF5())`. I mean, if you want to add and optimize one go for it. It's a really bad method that doesn't have a real use case though, so I don't see much of a point to specifically optimize it separately from

**Comment by zhaofeng-shu33** [comment]
Thanks. I found it from https://devdocs.sciml.ai/dev/internals/tableaus/
