### ISSUE TITLE
Error in Kvaerno4 tableau.

### ISSUE THREAD

**Issue by patrick-kidger** [SciML/OrdinaryDiffEq.jl#1501]
I think there's an error in the Kvaerno4 tableau. (Might be wrong, feel free to correct me.)

Based on the implementation [here](https://github.com/SciML/OrdinaryDiffEq.jl/blob/6fdc99fa4da79633e0161f0bb8aaff3f39cd39bc/src/perform_step/kencarp_kvaerno_perform_step.jl#L687), the solution is advanced according to the final stage.

However the tableau [here](https://github.com/SciML/OrdinaryDiffEq.jl/blob/6fdc99fa4da79633e0161f0bb8aaff3f39cd39bc/src/tableaus/sdirk_tableaus.jl#L1071) uses γ=0.4358665215, which corresponds to advancing the solution using the penultimate stage -- from Kvaerno's paper:
![image](https://user-images.githubusercontent.com/33688385/136950767-99016817-1f2b-4c8d-8850-4ee8f8ac3b4b.png)

So I think either (a) the solution should be advanced according to the penultimate stage, or (b) the value γ should be taken to be 0.5728160625, and the rest of the tableau updated accordingly. I've not tried this difference empirically so I don't know how meaningful the choice is.

**Comment by ChrisRackauckas** [comment]
Looks like you're correct. Probably best to not use local extrapolation because of the `c > 1` (and it would match ARKODE).
