### ISSUE TITLE
Dense Output Rodas5

### ISSUE THREAD

**Issue by gstein3m** [SciML/OrdinaryDiffEq.jl#1554]
The following program shows that dense output of Rodas5 is wrong for the algebraic components of DAE-problems:

using DifferentialEquations
using Plots

function dae!(dy, y, p, t)
    dy[1] = 3*t^2
    dy[2] = y[1] - y[2]
    nothing
end

#-- test dense output --
M = zeros(2,2); M[1,1] = 1.0
f = ODEFunction(dae!, mass_matrix = M);
y0 = [0.0; 0.0]; tspan = [0.0, 1.0];
prob = ODEProblem(f, y0, tspan, [])
sol = solve(prob, Rodas5())
println(sol.destats);
t = range(0.0,1.0,step = 0.1); 
scatter(t,t.^3, label = "exact sol")
plot!(sol)

I propose to implement dense output according to Rodas4/Rodas4p/Rodas4P2 with coefficients

h21= convert(T,31.040278745555575)
h22= convert(T,-6.925207756233034) 
h23= convert(T,41.54985263353498) 
h24= convert(T,-4.19983367949553) 
h25= convert(T,-20.0116097917112) 
h26= convert(T,-0.975683545855504) 
h27= convert(T,-1.0348884896058437) 

h31= convert(T,-1.3755295424732132) 
h32= convert(T,-1.1999290450148692e-12)
h33= convert(T,15.641155546064695) 
h34= convert(T,23.321973579898177) 
h35= convert(T,7.39545827189598)
h36= convert(T,-4.317455229088304) 
h37= convert(T,-3.409024912892793) 

Best regards 

Gerd

**Comment by ChrisRackauckas** [comment]
That sounds really exciting. I don't think standard Rosenbrocks are very useful for PDEs because of the lack of factorization reuse when it's not a W-method, but the improved stepsize selection would be welcome as it limits Rodas5 currently to the low tolerance regime.

**Comment by ChrisRackauckas** [comment]
Something is still odd in that `addsteps!` test. Locally:

(alg, x, x > 0.05, pass) = (Tsit5, 0.0010591442777936333, false, true)
(alg, x, x > 0.05, pass) = (Rosenbrock23, 0.0006732970356564394, false, true)
(DP5, 0.0011892070024144274, false, true)
(alg, x, x > 0.05, pass) = (DP8, 0.0009485483155975416, false, true)
(alg, x, x > 0.05, pass) = (SSPRK43, 4.440892098500626e-16, false, true)
(alg, x, x > 0.05, pass) = (SSPRK432, 4.440892098500626e-16, false, true)
(alg, x, x > 0.05, pass) = (OwrenZen3, 8.881784197001252e-16, false, true)
(alg, x, x > 0.05, pass) = (SSPRK22, 5.184849081185661e-7, false, true)
(alg, x, x > 0.05, pass) = (SSPRK33, 7.212008767965017e-13, false, true)
(alg, x, x > 0.05, pass) = (OwrenZen4, 8.23083152052817e-5, false, true)
(alg, x, x > 0.05, pass) = (OwrenZen5, 1.7763568394002505e-14, false, true)
(alg, x, x > 0.05, pass) = (Rosenbrock32, 0.0007098425541762765, false, true)
(alg, x, x > 0.05, pass) = (Rodas5, 0.00021890199215723882, false, true)
(alg, x, x > 0.05, pass) = (Rodas4, 0.0017055027804393497, false, true)
(alg, x, x > 0.05, pass) = (SSPRK22, 5.184849081185661e-7, false, true)
(alg, x, x > 0.05, pass) = (SSPRK33, 7.212008767965017e-13, false, true)
(alg, x, x > 0.05, pass) = (OwrenZen4, 8.23083152052817e-5, false, true)
(alg, x, x > 0.05, pass) = (OwrenZen5, 1.7763568394002505e-14, false, true)
(alg, x, x > 0.05, pass) = (Rosenbrock32, 0.0007098425541762765, false, true)
(alg, x, x > 0.05, pass) = (Rodas5, 0.00021890199215079953, false, true)
(alg, x, x > 0.05, pass) = (Rodas4, 0.0017055027804389056, false, true)
(alg, x, x > 0.05, pass) = (Rodas42, 0.002875320870291631, false, true)
```

vs CI: https://buildkite.com/julialang/ordinarydiffeq-dot-jl/builds/747#75d93991-5c22-47ae-9185-e68639b119b5/324-916

```julia
(x, x > 0.05, pass) = (0.0010591446745886746, false, true)
  | (x, x > 0.05, pass) = (0.0006732972646608104, false, true)
  | (x, x > 0.05, pass) = (0.0011892070024144274, false, true)
  | (x, x > 0.05, pass) = (0.0009485478314434914, false, true)
  | (x, x > 0.05, pass) = (4.440892098500626e-16, false, true)
  | (x, x > 0.05, pass) = (4.440892098500626e-16, false, true)
  | (x, x > 0.05, pass) = (8.881784197001252e-16, false, true)
  | (x, x > 0.05, pass) = (5.184849081185661e-7, false, true)
  | (x, x > 0.05, pass) = (7.212008767965017e-13, false, true)
  | (x, x > 0.05, pass) = (8.23083152052817e-5, false, true)
  | (x, x > 0.05, pass) = (1.7763568394002505e-14, false, true)
  | (x, x > 0.05, pass) = (0.0007098425541762765, false, true)
  | (x, x > 0.05, pass) = (0.0012211966086583814, false, true)
  | (x, x > 0.05, pass) = (0.0017055027804393497, false, true)
  | (x, x > 0.05, pass) = (0.0028753209053400397, false, true)
  | (x, x > 0.05, pass) = (0.0010591446745802369, false, true)
  | (x, x > 0.05, pass) = (0.0006732972646608104, false, true)
  | (x, x > 0.05, pass) = (0.0011892070024135393, false, true)
  | (x, x > 0.05, pass) = (0.0009485478314446016, false, true)
  | (x, x > 0.05, pass) = (4.440892098500626e-16, false, true)
  | (x, x > 0.05, pass) = (4.440892098500626e-16, false, true)
  | (x, x > 0.05, pass) = (8.881784197001252e-16, false, true)
  | (x, x > 0.05, pass) = (5.184849081185661e-7, false, true)
  | (x, x > 0.05, pass) = (7.212008767965017e-13, false, true)
  | (x, x > 0.05, pass) = (8.23083152052817e-5, false, true)
  | (x, x > 0.05, pass) = (1.7763568394002505e-14, false, true)
  | (x, x > 0.05, pass) = (0.0007098425541762765, false, true)
  | (x, x > 0.05, pass) = (0.001221196608646835, false, false)
  | (x, x > 0.05, pass) = (0.0017055027804389056, false, true)
  | (x, x > 0.05, pass) = (0.0028753209053391515, false, true)
```

I think there must be some aliasing or something.

**Comment by ChrisRackauckas** [comment]
Nope, I can recreate it now. And there's a clear failure. Highlighted in the plots:

```julia
using OrdinaryDiffEq, Test, Plots

function test_ode(u, p, t)
    [p[1] - (1 - p[1])*u[1]]
end

function test_ode(du, u, p, t)
    du[1] = p[1] - (1 - p[1])*u[1]
    return nothing
end

test_solution(t) = t <= 5 ? t : 5. * exp(-(t-5))

tspan = (0.,10.)
testtimes = range(tspan[1], stop=tspan[2], length=1001)
pullback_condition(u, t, i) = t - 5
pullback_affect!(i) = i.p[1] = abs(1 - i.p[1])
cb = ContinuousCallback(pullback_condition, pullback_affect!)

alg = Rodas4
inplace = true
prob = ODEProblem{inplace}(test_ode, [0.], tspan, [1.])
sol = solve(prob, alg(); callback=cb,dt=0.0013)
pass = all(isapprox(sol(t)[1], test_solution(t); atol=0.05) for t in testtimes)

plot(0.0:0.1:10.0,test_solution.(0.0:0.1:10.0))
plot!(sol)
savefig("plot1.png")

alg = Rodas5
inplace = false
prob = ODEProblem{inplace}(test_ode, [0.], tspan, [1.])
sol = solve(prob, alg(); callback=cb,dt=0.0013)
pass = all(isapprox(sol(t)[1], test_solution(t); atol=0.05) for t in testtimes)

plot(0.0:0.1:10.0,test_solution.(0.0:0.1:10.0))
plot!(sol)
savefig("plot2.png")

alg = Rodas5
inplace = true
prob = ODEProblem{inplace}(test_ode, [0.], tspan, [1.])
sol = solve(prob, alg(); callback=cb,dt=0.0013)
pass = all(isapprox(sol(t)[1], test_solution(t); atol=0.05) for t in testtimes)

plot(0.0:0.1:10.0,test_solution.(0.0:0.1:10.0))
plot!(sol)
savefig("plot3.png")
```

![plot1](https://user-images.githubusercontent.com/1814174/148453758-551aa640-92ce-4bb4-8218-399fe160c6ea.png)
![plot2](https://user-images.githubusercontent.com/1814174/148453756-c4c5b12f-5bb8-41f1-834a-f2e15bb49b2e.png)
![plot3](https://user-images.githubusercontent.com/1814174/148453757-12c0524d-ec0d-4003-9373-516caf9f035b.png)
