### ISSUE TITLE
Rosenbrock23 performs 3 rhs evaluations per step

### ISSUE THREAD

**Issue by simonbyrne** [SciML/OrdinaryDiffEq.jl#1587]
```
using OrdinaryDiffEq

function f!(du, u, p, t)
    println("f!: t=$t")
    du .= u
end

prob = ODEProblem(
    ODEFunction(
        f!;
        jac = (J, u, p, t) -> (J[1,1] = 1),
        jac_prototype = zeros(1,1),
        tgrad = (dT, u, p, t) -> fill!(dT, 0),
    ),
    [1.0],
    (0.0, 5.0),
)

sol = solve(
    prob,
    Rosenbrock23(),
    dt = 1.0,
    adaptive = false,
)
```

gives

```
f!: t=0.0
f!: t=0.0
f!: t=0.5
f!: t=1.0
f!: t=1.0
f!: t=1.5
f!: t=2.0
f!: t=2.0
f!: t=2.5
f!: t=3.0
f!: t=3.0
f!: t=3.5
f!: t=4.0
f!: t=4.0
f!: t=4.5
```

The 3 calls appear to be:

1. once in reset_fsal!  at time t https://github.com/SciML/OrdinaryDiffEq.jl/blob/774b202f20d63bd1011cfc0dc04d7e8035730b45/src/integrators/integrator_utils.jl#L391
2. once in calc_tderivative! also at time t https://github.com/SciML/OrdinaryDiffEq.jl/blob/0f74871e199148deec548d78feeff0b0ed9ad621/src/derivative_utils.jl#L37
3. once in perform_step! at time t+dt/2 https://github.com/SciML/OrdinaryDiffEq.jl/blob/e82fa88a79252357340e797f0ac18ca5dac55d38/src/perform_step/rosenbrock_perform_step.jl#L61

**Comment by ChrisRackauckas** [comment]
The `calc_tderivative!` one looks like a mistake that hid for 4 years, mostly because some tests would fail because they were assuming FSAL when they shouldn't have. A bit of clean up can remove that.

**Comment by simonbyrne** [comment]
Thanks, much appreciated!
