### ISSUE TITLE
`IMEXEuler()` is a multistep version, not the classical additive Runge-Kutta method version

### ISSUE THREAD

**Issue by ranocha** [SciML/OrdinaryDiffEq.jl#1590]
I ran into this issue while working on https://github.com/ranocha/BSeries.jl/pull/53. Given an additive partition of an ODE of the form
```
u'(t) = f1(u) + f2(u)
```
there are two different versions of "the" IMEX Euler method. What I would have expected is the classical additive Runge-Kutta method version as described by [Araújo, Murua, Sanz-Serna (1997)](https://doi.org/10.1137/S0036142995292128). This version reads as
```
y1   = uold + dt * f1(y1)
unew = uold + dt * (f1(y1) + f2(y1))
```
In OrdinaryDiffEq.jl, `IMEXEuler()` is the single-step version of the multistep methods of [Ascher, Ruuth, and Wetton (1995)](https://doi.org/10.1137/0732037), which can be written as
```
unew = uold + dt * (f1(unew) + f2(uold))
```

I guess it would be good to document this more explicitly - I will prepare a PR later today.

I think it would also make sense to implement an `IMEXEulerARK` or `AdditiveIMEXEuler` method (or however it would be called). What do you think?

**Comment by ChrisRackauckas** [comment]
Yes, you're right. And I actually completely forgot we had done this one in the style of SBDF1. Thanks. And you mean:

```julia
y1   = uold + dt * f1(y1)
unew = uold + dt * (f1(unew) + f2(y1))
```

yeah, it's whether the explicit portion is evaluated at an approximate unew or whether it's evaluated at uold. Both can probably share the same implementation with just a conditional in there to cut down on code, but agreed it's a bit confusing that there's these two "the IMEXEuler" and we should have both and clarify it.

**Comment by ranocha** [comment]
I agree with you that this is confusing and it would be great to have both variants :+1:
