### ISSUE TITLE
New 5(4) RK coefficients

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/OrdinaryDiffEq.jl#1601]
https://arxiv.org/abs/2202.08443

**Comment by dynamic-queries** [comment]
Found a similar 7th order method https://arxiv.org/pdf/2108.12590.pdf

**Comment by dynamic-queries** [comment]
- [ ] Implement 6th order method from table 4 - MSRK6
- [ ] Adaptive method MSRK54 and MSRK64

**Comment by pri1311** [comment]
Could give implementing the 6th order method a try.

**Comment by ChrisRackauckas** [comment]
It would be good to finish the 5h order method first. Adaptivity and interpolation. https://docs.sciml.ai/DiffEqDevDocs/stable/contributing/adding_algorithms/ is a good overview. Then see:

https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/src/tableaus/low_order_rk_tableaus.jl#L501-L609
https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/src/perform_step/low_order_rk_perform_step.jl#L903-L910

For how the adaptive estimates are computed using the btilde values. Let me know if you need any help there. One that and the interpolation are in, we can add it to our benchmarking suite: the author is curious about what the results will be.
