### ISSUE TITLE
New RK cofficients of Alshina, Zaks, and Kalitkin

### ISSUE THREAD

**Issue by ranocha** [SciML/OrdinaryDiffEq.jl#1610]
See 
- Alshina, Zaks, and Kalitkin (2008), Optimal first- to sixth-order accurate Runge-Kutta schemes, https://doi.org/10.1134/S0965542508030068
- Alshina, Zaks, and Kalitkin (2008), A misprint in the coefficients of Hammud’s scheme, https://en.num-meth.ru/index.php/journal/article/view/244

I couldn't find these schemes when using GitHub's search in this repo or in the documentation.

**Comment by ChrisRackauckas** [comment]
Yeah these ones aren't in the repo.
