### ISSUE TITLE
Erroneous function count incrementing in ROCK4

### ISSUE THREAD

**Issue by danielwe** [SciML/OrdinaryDiffEq.jl#1619]
No `f` was called to justify this function count increment:

https://github.com/SciML/OrdinaryDiffEq.jl/blob/e09b3457078b876ece2a6c13253186579b24da0e/src/perform_step/rkc_perform_step.jl#L373-L376

**Comment by ChrisRackauckas** [comment]
oh nice catch, yes that one should get deleted and we should add this solver to the list of methods we test the counts on.
