### ISSUE TITLE
Stochastic/occasional failure after a few timesteps

### ISSUE THREAD

**Issue by archermarx** [SciML/OrdinaryDiffEq.jl#1647]
Hi all,

I am working on a finite volume [simulation code](https://github.com/UM-PEPL/HallThruster.jl) which uses OrdinaryDiffEq for the timestepping. Overall, it works great. However, we have a problem where occasionally, without warning, the simulation will fail after a single timestep or a few timesteps. We will often have to rerun the same simulation with the exact same a few times in order to get one to complete. After this, it works fine for a while until we encounter this problem again and have to spam enter a few (1 - 15 or so) times until it runs. Predicting when this will happen or why it happens has eluded us so far, but today I was able to reproduce the problem with a minimum working example, where we solve linear advection on periodic boundary conditions:

Here's the MWE simulation code:

```julia
function step_function(;center = 0, width = 1, height = 1.0)
    step_func = x -> let center=center, width=width, height=height
        height * (abs(x - center) ≤ width/2)
    end
    return step_func
end

function solve_advection(end_time; ncells, nsave, advection_velocity, initial_condition = step_function(center = 0.5, width = 0.2), alg = SSPRK22())
    grid = LinRange(0.0, 1.0, ncells)
    saveat = LinRange(0.0, end_time, nsave)
    params = (;advection_velocity, grid)

    # The state matrix is set up this way in order to mimic the setup in HallThruster.jl, where we have some cells which
    # do not get updated by the OrdinaryDiffEq timestepping (boundary cells and the parts which we integrate implicitly)
    # Here, we have one state variable which represents the density of the advected quantity and which is updated by 
    # OrdiinaryDiffEq, and one which is untouched by OrdinaryDiffEq
    u = ones(2, ncells)
    u[1, :] = initial_condition.(grid)' |> collect
    u[2, :] = advection_velocity * ones(ncells)
    prob = ODEProblem{true}(update!, u, (0.0, end_time), params)

    dt = 0.9 * (grid[2] - grid[1]) / advection_velocity

    sol = solve(prob, alg; saveat, dt, adaptive=false)
    return sol
end

function update!(du, u, p, t)
    (;advection_velocity, grid) = p

    Δx = grid[2] - grid[1]

    for (i, x) in enumerate(grid)
        i_plus_1  = i == lastindex(grid)  ? firstindex(grid) : i+1
        i_minus_1 = i == firstindex(grid) ? lastindex(grid)  : i-1

        a⁺ = advection_velocity * (advection_velocity > 0)
        a⁻ = advection_velocity * (advection_velocity < 0)

        uL = u[1, i_minus_1]
        u0 = u[1, i]
        uR = u[1, i_plus_1]

        du[1, i] = - (a⁺ * (u0 - uL) / Δx + a⁻ * (uR - u0) / Δx)
    end

    return du
end

sol  = solve_advection(1.0; ncells = 100, nsave = 100, advection_velocity = 1, alg = SSPRK22())
```

This _almost always_ works. However, every so often it fails with `:Unstable` and we get the `Instability detected. Aborting` message. To better characterize this problem, I set up a stress test:

```julia
function stress_test(n, timesteps = 2; alg)
    advection_velocity = 5 * rand()
    ncells = rand(5:200)
    dt = 0.9 / ncells / advection_velocity
    count = 0
    time = timesteps * dt

    sol = solve_advection(time; ncells, nsave = timesteps+1, advection_velocity)

    sols = typeof(sol)[]
    fail_iters = Int[]

    for i in 1:n-1
        if sol.retcode != :Success
            count += 1
            push!(fail_iters, i)
            push!(sols, sol)
        end
        sol = solve_advection(time; ncells, nsave = timesteps+1, advection_velocity)
    end

    return fail_iters, sols
end
```

This generates random advection velocities and cell numbers and runs many identical simulations with these randomly-generated parameters, saving the solutions which fail and their corresponding iterations. This let me reproduce the problem a bit more consistently, as in a batch of 10000 simulations i would occasionally get one in which 3 or so failed, while most batches succeeded. Looking at the plots, it seemed that the problem lay in the second dummy state variable.

Interestingly, if change the following lines in the advection code:

```julia
u = ones(2, ncells)
u[1, :] = initial_condition.(grid)' |> collect
u[2, :] = advection_velocity * ones(ncells)
```

to

```julia
u = ones(1, ncells)
u[1, :] = initial_condition.(grid)' |> collect
```

the simulation doesn't fail ever. Similarly, if I manually set

```julia
du[2, i] = 0.0
```

the the simulation never fails. I had been assuming that if I don't set du, then du = 0 is assumed. This appears to be the case most of the time, but very rarely this doesn't seem to be true. I tested this with every third order SSP scheme, Euler(), RK4(), and Tsit5() and all exhibit this behavior. 

Proposed fix would be 
1) setting du .= 0 at the beginning, or
2) adding a warning in the documentation that you need to set dU = 0 manually if you have state variables which aren't changing (I know this isn't the best way to handle these problems, and I'm open to suggestions on how to better handle boundary conditions and the like).

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/SciML/OrdinaryDiffEq.jl/pull/1648
