### ISSUE TITLE
nonstifftol is apparently no more recognized as keyword argument

### ISSUE THREAD

**Issue by andreasvarga** [SciML/OrdinaryDiffEq.jl#1659]
Until today, I used the following call

`sol = solve(prob, AutoVern9(Rodas5()); nonstifftol = 11/10, reltol, abstol, save_evrystep = false)`

After an update to OrdinaryDiffEq v5.71.1 I got the message
```
Warning: Warning: Unrecognized keyword arguments found. Future versions will error.
│ The only allowed keyword arguments to `solve` are:
│ (:dense, :saveat, :save_idxs, :tstops, :d_discontinuities, :save_everystep, :save_on, :save_start, :save_end, :initialize_save, :adaptive, :abstol, :reltol, :dt, :dtmax, :dtmin, :force_dtmin, :internalnorm, :controller, :gamma, :beta1, :beta2, :qmax, :qmin, :qsteady_min, :qsteady_max, :qoldinit, :failfactor, :calck, :alias_u0, :maxiters, :callback, :isoutofdomain, :unstable_check, :verbose, :merge_callbacks, :progress, :progress_steps, :progress_name, :progress_message, :timeseries_errors, :dense_errors, :calculate_errors, :initializealg, :alg, :save_noise, :delta, :seed, :alg_hints, :kwargshandle, 
:trajectories, :batch_size, :sensealg, :advance_to_tstop, :stop_at_next_tstop, :default_set, :second_time)
│ See https://diffeq.sciml.ai/stable/basics/common_solver_opts/ for more details.
```
I changed `save_evrystep = false` to `save_everystep = false` , here and in several other similar calls, but with the following call

`     sol = solve(prob, AutoVern9(Rodas5()); nonstifftol = 11/10, reltol, abstol, save_everystep = false)`

I  am still receiving the same message. However, the following call works

`
         sol = solve(prob, AutoVern9(Rodas5()); reltol, abstol, save_everystep = false)`

I was not able to find out the new calling scheme with the same effect. Many thanks for any hints.

**Comment by YingboMa** [comment]
`nonstifftol` was never an option in `solve`. It's an option of `AutoVern9`.

**Comment by ChrisRackauckas** [comment]
`AutoVern9(Rodas5(), nonstifftol = 11/10)`. The issue is that we didn't have those warnings earlier, but better late than never 😅

**Comment by andreasvarga** [comment]
Thanks.
