### ISSUE TITLE
setindex!(::SVector{3, Float64}, value, ::Int) in StaticArrays is not defined when doing reinit!

### ISSUE THREAD

**Issue by jarroyoe** [SciML/OrdinaryDiffEq.jl#1689]
Today I updated my packages in Julia v1.6.2. I had an issue when running a function of ChaosTools.jl and opened a bug there:
https://github.com/JuliaDynamics/ChaosTools.jl/issues/260

Seems that there is a bug in the reinit! function which makes it fail with some solvers. @Datseris kindly provided this MWE in that thread:
```
using OrdinaryDiffEq, StaticArrays

function eq(N,p,t)
    dN1 = ((N[2]*N[3]) / (1.0 + N[2]^2))
    dN2 = ((N[3]*N[2]) / (1.0 + N[3]^2)) - ((N[2]*N[3]) / (1.0 + N[2]^2))
    dN3 = N[3]*(1.0 - N[3]) - ((N[3]*N[2]) / (1.0 + N[3]^2))
    return SVector{3}(dN1,dN2,dN3)
end

system = ODEProblem(eq,@SVector([0.0,0.0,0.0]), (0.0, 100.0), nothing)
integ = init(system, Vern9(); reltol = 1e-16, abstol = 1e-16)
step!(integ) # works
reinit!(integ, [0.0, 0, 0]) # doesn't
reinit!(integ, @SVector([0.0, 0, 0])) # also doesn't
```
This was not happening before updating the packages.

**Comment by ChrisRackauckas** [comment]
Duplicate https://github.com/SciML/OrdinaryDiffEq.jl/issues/1688
