### ISSUE TITLE
Callback error when using StaticArrays

### ISSUE THREAD

**Issue by TomRottier** [SciML/OrdinaryDiffEq.jl#1714]
For my use case I define my u as a SVector and have a callback terminate the integration when some function of u is met. However I am now getting an error as `setindex!` is getting called on u. I have multiple models set up like this but never encountered this problem before. MWE below:

```julia
using StaticArrays, OrdinaryDiffEq

f(u, p, t) = SVector(p * u[1])
u0 = SVector(0.1)
p = 0.1
tspan = (0.0, 100.0)
prob = ODEProblem(f, u0, tspan, p)
condition(u, t, int) = 10 - u[1]
affect!(int) = nothing
affect_neg!(int) = terminate!(int)
cb = ContinuousCallback(condition, affect!, affect_neg!)

sol = solve(prob, Tsit5(), abstol=1e-8, reltol=1e-8, callback=cb)
```

Error produced:
```julia
ERROR: setindex!(::SVector{1, Float64}, value, ::Int) is not defined.
```

**Comment by ChrisRackauckas** [comment]
Are you on the most recent version? I cannot recreate with `[1dea7af3] OrdinaryDiffEq v6.19.3`. If with current versions you still have an issue, please share `]st` and `]st -m`.

**Comment by TomRottier** [comment]
Apologies I thought I had but some other package was preventing it upgrading. Working now thanks
