### ISSUE TITLE
`SplitFunction` causes instability in split ode solvers

### ISSUE THREAD

**Issue by superckl** [SciML/OrdinaryDiffEq.jl#1730]
Using a `SplitFunction` seems to cause instabilities in split ode solvers such as `KenCarp4`. A test case is given below where a fourth-order PDE is solved by finite differences. The standard `ODEFunction` formulation works fine. However, using a `SplitFunction` with a dummy `f2` causes immediate instablity while I would expect it to be functionally equivalent.

https://gist.github.com/superckl/3d03324c1aee64a40a1cf3b5acf97c7f.

**Comment by ranocha** [comment]
Do you also get the warning mentioned in #1726?

**Comment by superckl** [comment]
No, I've seen no such warning.

**Comment by superckl** [comment]
A few more comments:

1. The two cases are identical when using `ARKODE`, so this seems to be something with `OrdinaryDiffEq.jl` solvers.
2. Even for situations where `KenCarp` succeeds, the two cases produce slightly different results .
