### ISSUE TITLE
non-adaptive `step!` can get stuck in infinite loop

### ISSUE THREAD

**Issue by bradcarman** [SciML/OrdinaryDiffEq.jl#1769]
If using iterator_interface.jl `step!(integrator::ODEIntegrator)` and we get `integrator.accept_step=false` then we enter the `while` loop.  If then `perform_step!`  hits `nlsolvefail(nlsolver) = true` (in sdirk_perform_step.jl) then we will never exit the while loop.  When entering the `loopfooter` I can see that `integrator.last_stepfail = true`, therefore the `loopfooter` simply returns and the `while` loop continues.

**Comment by ChrisRackauckas** [comment]
It will decrease dt each time and that will quickly cause an exit with a dt hitting dtmin

**Comment by bradcarman** [comment]
Sorry I failed to mention this is non-adaptive case

**Comment by ChrisRackauckas** [comment]
Then it should exist at `maxiters`?

**Comment by bradcarman** [comment]
OK, I can't reproduce the issue anymore.  Something between OrdinaryDiffEq v6.26.4 and 6.27.2 fixed the problem
