### ISSUE TITLE
Saving Jacobians created

### ISSUE THREAD

**Issue by gstein3m** [SciML/OrdinaryDiffEq.jl#1773]
using DifferentialEquations

function ode_foo(du, u, p, t)
 du[1] = u[1] + t^10
end

prob = ODEProblem(ode_foo, [0.0], (0.0, 1.0))
sol = solve(prob, Rodas4())
println(sol.destats)

gives the statistics: 

Number of function 1 evaluations:                  210
Number of function 2 evaluations:                  0
Number of W matrix evaluations:                    26
Number of linear solves:                           156
Number of Jacobians created:                       26
Number of nonlinear solver iterations:             0
Number of nonlinear solver convergence failures:   0
Number of rootfind condition calls:                0
Number of accepted steps:                          21
Number of rejected steps:                          5

Rosenbrock methods need only a new W matrix but not a new Jacobian when a step is rejected. Thus only 21 Jocobians would be required?

**Comment by ChrisRackauckas** [comment]
Thanks! Yes, that does look like it could save some calculations. @YingboMa is investigating it in #1780
