### ISSUE TITLE
Model with DFBDF is in v6.30 unstable

### ISSUE THREAD

**Issue by ValentinKaisermayer** [SciML/OrdinaryDiffEq.jl#1787]
I have a set of MTK models that I run nighlty tests on and since yesterday one keeps failing. It is a thermofluid network. I get an `SciMLBase.ReturnCode.DtLessThanMin` now with v6.30 and `DFBDF`, which worked up to now. From my test logs it seems to be the only dependency difference.

I know this isn't so helpful without a MWE.

**Comment by YingboMa** [comment]
BTW, is it deliberate to not use `ODEProblem`, or is that just a test for coverage?

**Comment by ValentinKaisermayer** [comment]
I use an ODEProblem on the same problem as well, it still worked.
