### ISSUE TITLE
Auto-differentiation failure when using DiffResults

### ISSUE THREAD

**Issue by thomvet** [SciML/OrdinaryDiffEq.jl#1797]
In the following MWE of my actual code (which is much larger in terms of equations and LOC), I am trying to stay completely allocation free in my definition of the differential equations. Even when calculating a gradient using ForwardDiff. This works fine as long as no Dual numbers are coming from the ODE solver, but throws a MethodError otherwise (with >30 level deep stacktrace):
```
using DifferentialEquations, DiffResults, ForwardDiff

g(x) = x[1] + x[2]
cache = DiffResults.GradientResult(zeros(2))
gradientcfg = ForwardDiff.GradientConfig(g, zeros(2)) #deactivates tag-checking; otherwise, getting invalid tag error; not encouraging of course

function diffeq1!(dstatesdt, states, parameters, time)
    diffresultscache = parameters[1]
    gradientcfg = parameters[2]
    ForwardDiff.gradient!(diffresultscache, g, states, gradientcfg)
    dstatesdt[1] = -states[1]
    dstatesdt[2] = -DiffResults.value(diffresultscache)
    return nothing
end

initialstates = [2.0, 1.0]
parameters = (cache, gradientcfg)
odeproblem = ODEProblem{true}(diffeq1!, initialstates, (0.0, 5.0), parameters)
du = similar(initialstates)

solution = solve(odeproblem, Tsit5()) #works
allocs = @allocated diffeq1!(du, initialstates, parameters, 0.0) #0 allocations
solution = solve(odeproblem, Rosenbrock23()) #MethodError involving Dual numbers

```

Thinking about this some more, maybe this is actually an issue with DiffResults or maybe I should have a caching method like PreallocationTools's dualcache (but with items from DiffResults...). 

Going through the stacktrace, it looks like that the cache object (diffresultscache) generated by DiffResults is not able to hold Dual numbers? 

Ideas to circumvent this or fix this? I do have these two options of course:
1) circumventing the issue with solve(... autodiff = false)
2) just taking the hit in terms of allocations when calculating the gradient (i.e., using ForwardDiff.gradient(...) instead of ForwardDiff.gradient!(...))

But before I go down that hole and take the performance hit (...), I wanted to check whether there are smarter alternatives.

**Comment by ChrisRackauckas** [comment]
> Thinking about this some more, maybe this is actually an issue with DiffResults or maybe I should have a caching method like PreallocationTools's dualcache (but with items from DiffResults...).

Yes. `#MethodError involving Dual numbers` because it's the wrong dual numbers, the wrong tag, and the wrong chunk size. See the FAQ, or use something from PreallocationTools.
