### ISSUE TITLE
Move `alg_order` to SciMLBase

### ISSUE THREAD

**Issue by charleskawczynski** [SciML/OrdinaryDiffEq.jl#1825]
We're working on some custom time steppers in ClimaTimeSteppers, and we've been able to nicely extend things using DiffEqBase (e.g., `DiffEqBase.AbstractODEAlgorithm`) and remain compatible with OrdinaryDiffEq. One thing I realized, however, is that to extend `alg_order`, we either need to do one of the following:

 - Directly depend on OrdinaryDiffEq, which seems a shame since it's not technically needed for for anything except the test suite. This isn't really a problem, except that we're trying to keep our dependencies slim

 - Only overload `OrdinaryDiffEq.alg_order` in the test suite (which is what I'm temporarily leaning towards)

 - Have `alg_order` moved to DiffEqBase. This seems ideal since `AbstractODEAlgorithm` is defined there and that's the only argument to `alg_order`

It doesn't seem like too much work, mind if I open a few PRs?

**Comment by ChrisRackauckas** [comment]
Yeah, it seems like a good thing to move.

**Comment by charleskawczynski** [comment]
Closed by https://github.com/SciML/SciMLBase.jl/pull/451
