### ISSUE TITLE
Update dependence of Polyester.jl to v0.7

### ISSUE THREAD

**Issue by PhyX-Meow** [SciML/OrdinaryDiffEq.jl#1828]
Due to the update of [PolyesterWeave.jl](https://github.com/JuliaSIMD/PolyesterWeave.jl), precompile will fail with Polyester@0.6.20, so they updated Polyester version to v0.7 and fixed the problem. But for now compatibility of [OrdinaryDiffEq.jl](https://github.com/SciML/OrdinaryDiffEq.jl) prevents it to update, and then all packages behind them cannot pass precompile.

I looked into the release and found no critical change in main functionality. So maybe we just need to update compat.
Thank you!

**Comment by ChrisRackauckas** [comment]
@chriselrod what's going on here? https://github.com/SciML/OrdinaryDiffEq.jl/pull/1829 v0.7 fails as well.

**Comment by ChrisRackauckas** [comment]
https://github.com/YingboMa/FastBroadcast.jl/commit/d3441753f8e9f4d321a698891015e87863fba9b9 looks like it needs to be tagged.

**Comment by ChrisRackauckas** [comment]
The yank should have fixed this.
