### ISSUE TITLE
Trapezoid docstring

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/OrdinaryDiffEq.jl#1838]
https://docs.sciml.ai/OrdinaryDiffEq/stable/stiff/sdirk/#OrdinaryDiffEq.Trapezoid

via divided ...

**Comment by ChrisRackauckas** [comment]
Solved with a quick https://github.com/SciML/OrdinaryDiffEq.jl/commit/a52c51c365a73b427432f195738e21dc2a5e4c14
