### ISSUE TITLE
Issues precompiling

### ISSUE THREAD

**Issue by pkairys** [SciML/OrdinaryDiffEq.jl#1861]
Hi, I'm having issues precompiling OrdinaryDiffEq. 

Specifically, when precompiling my project with OrdinaryDiffEq as a dependency I get this error:

> ERROR: LoadError: LoadError: syntax: local variable name "tmp" conflicts with an argument
Stacktrace:
  [1] top-level scope
    @ ~/.julia/packages/OrdinaryDiffEq/pIBDs/src/perform_step/explicit_rk_perform_step.jl:141
  [2] include(mod::Module, _path::String)
    @ Base ./Base.jl:384
  [3] include(x::String)
    @ OrdinaryDiffEq ~/.julia/packages/OrdinaryDiffEq/pIBDs/src/OrdinaryDiffEq.jl:4
  [4] top-level scope
    @ ~/.julia/packages/OrdinaryDiffEq/pIBDs/src/OrdinaryDiffEq.jl:166
  [5] include
    @ ./Base.jl:384 [inlined]
  [6] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base ./loading.jl:1235
  [7] top-level scope
    @ none:1
  [8] eval
    @ ./boot.jl:360 [inlined]
  [9] eval(x::Expr)
    @ Base.MainInclude ./client.jl:446
 [10] top-level scope
    @ none:1
in expression starting at /home/pkairys/.julia/packages/OrdinaryDiffEq/pIBDs/src/perform_step/explicit_rk_perform_step.jl:141
in expression starting at /home/pkairys/.julia/packages/OrdinaryDiffEq/pIBDs/src/OrdinaryDiffEq.jl:1

Is this potentially related to [this merge](https://github.com/SciML/OrdinaryDiffEq.jl/pull/1851)? It looks like prior to this change there wasn't even a line 141 in the file. 

Maybe this is just on my end. I will try pinning an earlier version of OrdinaryDiffEq to see if it makes a difference.

**Comment by ChrisRackauckas** [comment]
Did you update and it worked out? All tests passed so it should be fine. Are you using a generic Julia binary from https://julialang.org/downloads/ ?
