### ISSUE TITLE
Make these tests use `MethodOfLInes`

### ISSUE THREAD

**Issue by vpuri3** [SciML/OrdinaryDiffEq.jl#1868]
and remove `DiffEqOperators` dependency from OrdinaryDiffEq.

https://github.com/SciML/OrdinaryDiffEq.jl/blob/ca6f5bd4abdf2b1a569af1b783c33e2effd431e5/test/interface/nonfulldiagonal_sparse.jl#L1

@xtalax

**Comment by xtalax** [comment]
@ChrisRackauckas what system is this so I can move it over to MOL, the time has come to soft deprecate MOL

**Comment by ChrisRackauckas** [comment]
I'm not sure you can represent such a solve in MOL. But the point of the test is that it doesn't have a full diagonal in the sparse matrix, which needs to be corrected in the sparse handling code. So it could be transformed into a unit test and dropped for something which has an incomplete diagonal Jacobian.
