### ISSUE TITLE
Developer option to turn off precompilation

### ISSUE THREAD

**Issue by xtalax** [SciML/OrdinaryDiffEq.jl#1911]
Developing in SciMLBase, and this package is significantly slowed by the need to precompile this package, it would be good to have an option to turn off the precomopiling solves while doing this.

**Comment by ChrisRackauckas** [comment]
Those already exist https://docs.sciml.ai/DiffEqDocs/stable/features/low_dep/#Controlling-Function-Specialization-and-Precompilation
