### ISSUE TITLE
sol.retcode == :Success is not recognized correctly

### ISSUE THREAD

**Issue by Denis-Titov** [SciML/OrdinaryDiffEq.jl#1916]
I run the following code from the readme:

```
f(u,p,t) = 1.01*u
u0=1/2
tspan = (0.0,1.0)
prob = ODEProblem(f,u0,tspan)
sol = solve(prob,Tsit5(),reltol=1e-8,abstol=1e-8)
sol.retcode == :Success #false
Symbol(sol.retcode) == :Success #true
```

`sol.retcode == :Success` is false even though `Symbol(sol.retcode) == :Success` is true

This used to work correctly but stopped working now.

I used Julia 1.9.0-rc1 and DifferentialEquations v7.7.0

**Comment by oscardssmith** [comment]
It's been deprecated for a while and should now be `sol.retcode == ReturnCode.Success`.

**Comment by ChrisRackauckas** [comment]
That's not in the README? I don't see any `sol.retcode` in the README? Let me know if there's a spot that's still using the old check but I can't find it.

**Comment by Denis-Titov** [comment]
I saw `sol.retcode != :Success` in documentation here: https://docs.sciml.ai/DiffEqDocs/stable/basics/faq/#My-ODE-is-solving-really-slow

And that's why I started using `sol.retcode == :Success`, which stopped working.
Sorry `sol.retcode` is not in README. I meant the ODE example is from README not `sol.retcode` part

**Comment by ChrisRackauckas** [comment]
Cool fixed https://github.com/SciML/DiffEqDocs.jl/commit/3d5ee28e377d1c371a165e5d40996992bc26711b

**Comment by hhuber2512** [comment]
Hello,

There's another usage of 
```
sol.retcode != :Success
``` 
in the SciML documentation, here: https://docs.sciml.ai/DiffEqParamEstim/stable/methods/optimization_based_methods/

It also comes up in the Turing.jl documentation, when they're discussing Bayesian inference with Differential Equations: https://turinglang.org/v0.25/tutorials/10-bayesian-differential-equations/

**Comment by ChrisRackauckas** [comment]
> in the SciML documentation, here: https://docs.sciml.ai/DiffEqParamEstim/stable/methods/optimization_based_methods/

Thanks, just fixed that one.

**Comment by ChrisRackauckas** [comment]
>  It's been deprecated for a while and should now be sol.retcode == ReturnCode.Success.

`SciMLBase.successful_retcode(sol)`. See https://docs.sciml.ai/SciMLBase/stable/interfaces/Solutions/#Return-Code-Traits
