### ISSUE TITLE
Module loading sequence hang with TaylorIntegration.jl

### ISSUE THREAD

**Issue by vram0gh** [SciML/OrdinaryDiffEq.jl#1931]
When using `OrdinaryDiffEq.jl` and `TaylorIntegration.jl` together, the sequence of `using` statements always has to be:

```
using OrdinaryDiffEq
using TaylorIntegration
```

in that order, otherwise a hang occurs.  For example, this hangs:

```
using TaylorIntegration
using OrdinaryDiffEq
```

and so does this even though the `using` statements occur in sister modules:

```
module ModTIOnly
  using TaylorIntegration
end

module ModODEjlOnly
  using OrdinaryDiffEq
end
```

Versions: Julia 1.8.5 on Linux/x86-64, OrdinaryDiffEq v6.50.0 , TaylorIntegration v0.11.1

**Comment by ChrisRackauckas** [comment]
Open the issue on TaylorIntegration.jl. There's nothing to do here since it's a downstream issue.
