### ISSUE TITLE
Unexpected sign changes with intermediate states of `ROCK2`, `ROCK4`, `RKC`, `ESERK4`, `ESERK5`

### ISSUE THREAD

**Issue by jlchan** [SciML/OrdinaryDiffEq.jl#1932]
I'm observing some strange sign changes with respect to intermediate states for all explicit stabilized Runge-Kutta methods. Here's a MWE solving `u' = 0`:
```julia
using OrdinaryDiffEq
u = ones(2)
function rhs!(du, u, p, t)    
    @show u
    fill!(du, zero(eltype(du)))
end
ode = ODEProblem(rhs!, u, (0.0, .1))
sol = solve(ode, ROCK2(), dt=.2, adaptive=false)
```
The truncated output is
```julia
u = [1.0, 1.0]
u = [0.0, 0.0]
u = [1.0000000149011612, 1.0000000149011612]
u = [1.0000000149011612, -1.0000000149011612]
u = [-1.0000000149011612, -1.0000000149011612]
u = [-1.0000000149011612, 1.0000000149011612]
...
```
I think the solution can be expected to change sign given lines like https://github.com/SciML/OrdinaryDiffEq.jl/blob/0e2eb2c62bc50ddd4d5f3c8af28c69d9c27b4334/src/perform_step/rkc_perform_step.jl#L116
However, it seems strange that the sign change doesn't happen for every solution component. 

Similar component-wise sign-flipping behavior is observed for at least one intermediate state when using `ROCK4`, `RKC`, `ESERK4`, or `ESERK5` as well. @ranocha FYI

**Comment by ranocha** [comment]
It looks like all these "weird" values come from the eigenvalue estimate in
https://github.com/SciML/OrdinaryDiffEq.jl/blob/2e6400d76b7c2407cc8553afed41b9131c17e23f/src/rkc_utils.jl#L102-L202

**Comment by ChrisRackauckas** [comment]
Which is kind of like a differentiation / Jacobian approximation in a sense. So I don't think it's too surprising?

**Comment by ranocha** [comment]
Well, it makes it impossible to use for something like Navier-Stokes in Trixi.jl where you get into severe trouble when the density gets negative...

**Comment by ChrisRackauckas** [comment]
For a case like that you'd probably want to provide an eigenvalue estimate and skip that whole phase. It would make things a lot faster too. In PDEs you're likely to know the CFL or have an easily available estimate for it?

**Comment by ranocha** [comment]
Is there some documentation how the maximum eigenvalue estimation should work?

In general, we do like error-based step size control (see http://arxiv.org/abs/2104.06836 and http://arxiv.org/abs/2209.07037) since it is a highly non-trivial issue to get a good CFL estimate for high-order methods on curved meshes in multiple dimensions. Thus, if there is a nice way to automate the process, we would be very happy. But maybe this is a genuine research project and we should try manual estimates first.

**Comment by jlchan** [comment]
Specifying a maximum eigenvalue estimate is possible, but it's not clear on what `eigen_est` should be returning. I've tried (for the heat equation) the largest eigenvalue by magnitude, the absolute value of the largest magnitude eigenvalue, and 1. None of them give as good performance as `ROCK4()`'s built in eigenvalue estimate.

**Comment by jlchan** [comment]
Bump - any documentation on how to use `eigen_est` or skip this step entirely? I'd be happy to add this to SciMLDocs...

**Comment by ChrisRackauckas** [comment]
No docs right now, just a function of the integrator as shown in the tests https://github.com/SciML/OrdinaryDiffEq.jl/blob/b7bb73f46669e6f35c33baf2b4a1a1dc9892a091/test/algconvergence/rkc_tests.jl#L10 .
