### ISSUE TITLE
Analysis of time spent precompiling

### ISSUE THREAD

**Issue by KristofferC** [SciML/OrdinaryDiffEq.jl#1937]
With the new profiling tools in Julia it is now easier to get a good look at what happens during precompilation. Since OrdinaryDiffEq has a quite large compilation time, I did a bit of analysis.

The profile trace can be seen online in https://topolarity.github.io/trace-viewer/?trace=https%3A%2F%2Fraw.githubusercontent.com%2FKristofferC%2Ftracy-traces%2Fmain%2Forddiffeq_precompile.tracy&size=9821725.

The top sections where time is spent is:

![image](https://github.com/SciML/OrdinaryDiffEq.jl/assets/1282691/5d3d78a3-f0d8-49c4-a159-64f61d226b3b)

So in summary, we are compiling a lot of different methods which means we have to infer and compile them. Not strange.

These are the inference time of the different methods that take the most time:

![gnome-shell-screenshot-bctd16](https://github.com/SciML/OrdinaryDiffEq.jl/assets/1282691/33368da7-c176-4976-a787-91fc28f44fb4)

One perhaps interesting note is that it seems we are compiling 28 versions of `solve_call` with a `CompositeAlgorithm`. That seems like a lot? Each such `solve_call` seems to take around 500ms to infer:

![gnome-shell-screenshot-921r89](https://github.com/SciML/OrdinaryDiffEq.jl/assets/1282691/5fd8f39d-1335-4680-98e8-d44f4c6c7041)

Some possible ways to improve things:

- Precompile fewer solvers by default and leave it up to users of the package to precompile their specific workloads.
- Maybe look into why 28 versions of `CompositeAlgorithm` is precompiled.
- Try to make fewer things specialize on the concrete algorithm so that compiling each algorithm is cheaper.

**Comment by KristofferC** [comment]
Cost per combination is the same but the number of combinations seems to have been reduced a lot by default.

**Comment by gdalle** [comment]
Out of curiosity what "new profiling tools" did you use?

**Comment by KristofferC** [comment]
Tracy, https://docs.julialang.org/en/v1/devdocs/external_profilers/
