### ISSUE TITLE
Out of place exponential Krylov regression

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/OrdinaryDiffEq.jl#1956]
In https://github.com/SciML/OrdinaryDiffEq.jl/pull/1951 it was found that the linear Krylov tests were failing. https://github.com/SciML/OrdinaryDiffEq.jl/pull/1954 showed that those tests were failing on master. The last major change to this part of the code was https://github.com/SciML/OrdinaryDiffEq.jl/pull/1917, which makes sense because the Krylov methods use the SciMLOperators directly, so something must have happened with the OOP definition of `*` and its usage from SplitODEFunction.

In the code, there was an issue that was found that it didn't have an OOP update_func, https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/test/algconvergence/linear_nonlinear_krylov_tests.jl#L19 which meant it wasn't testing much. This needed a fix in https://github.com/SciML/SciMLBase.jl/commit/e4f2a5a3f4414941b2c365b3c5733eb9940c9f3f so the jac was correct, and then it was noticed that the values were off. Now 
 https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/test/algconvergence/linear_nonlinear_krylov_tests.jl has the OOP tests in skip mode, but this is a pretty bad regression so we should make sure this gets a good look ASAP. I think it would be hard to revert the SciMLOperators + SparseDiffTools + LinearSolve updates, so I think we just need to figure out what regressed and handle it.

@gaurav-arya @vpuri3

**Comment by vpuri3** [comment]
Very weird: LawsonEuler, NorsettEuler fail but ETDRK2 is fine. ETDRK3 breaks, but ETDRK4 is fine.

**Comment by vpuri3** [comment]
And the errors go away if you reduce the time-step size.
```julia
julia> include("a/a.jl")
[ Info: LawsonEuler, dt = 0.001
isapprox(sol(1.0), sol_ref(1.0); rtol = tol) = true
LawsonEuler
[ Info: NorsettEuler, dt = 0.001
isapprox(sol(1.0), sol_ref(1.0); rtol = tol) = true
NorsettEuler
[ Info: ETDRK2, dt = 0.001
isapprox(sol(1.0), sol_ref(1.0); rtol = tol) = true
ETDRK2
[ Info: ETDRK3, dt = 0.005
isapprox(sol(1.0), sol_ref(1.0); rtol = tol) = true
ETDRK3
[ Info: ETDRK4, dt = 0.005
isapprox(sol(1.0), sol_ref(1.0); rtol = tol) = true
ETDRK4
[ Info: HochOst4, dt = 0.005
isapprox(sol(1.0), sol_ref(1.0); rtol = tol) = true
```

**Comment by vpuri3** [comment]
looks like as you refine the simulation (decrease dt) the test is converging to the right solution. so update behavior is fine??

i see that you are providing both dt and reltol here

https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/test/algconvergence/linear_nonlinear_krylov_tests.jl#LL30C17-L30C17

what behavior is expected here if dt is too large for the tolerance?

**Comment by ChrisRackauckas** [comment]
It looks like that fails? I did that here:  https://github.com/SciML/OrdinaryDiffEq.jl/pull/1960
