### ISSUE TITLE
Link in `symplectic_perform_step.jl` is broken

### ISSUE THREAD

**Issue by Web3NL** [SciML/OrdinaryDiffEq.jl#1978]
trying to find the pdf

http://www.chimica.unipd.it/antonino.polimeno/pubblica/downloads/JChemPhys_101_4062.pdf

https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/src/perform_step/symplectic_perform_step.jl

**Comment by ErikQQY** [comment]
The original paper can be found on researchgate: https://www.researchgate.net/profile/Stephen-Gray-2/publication/253544574_Symplectic_integrators_for_large_scale_molecular_dynamics_simulations_A_comparison_of_several_explicit_methods/links/0a85e538496e30afc1000000/Symplectic-integrators-for-large-scale-molecular-dynamics-simulations-A-comparison-of-several-explicit-methods.pdf
