### ISSUE TITLE
Use `ExponentialUtilities.exponential!` instead of `exp` and add `method` as an option in solvers that currently use `exp` and `expv`

### ISSUE THREAD

**Issue by howsiyu** [SciML/OrdinaryDiffEq.jl#2009]
As per title. My main motive for this is that `exp` doesn't support AD (https://github.com/JuliaDiff/ForwardDiff.jl/issues/174). This shouldn't affect existing code if we set the default method to be [ExpMethodNative](https://docs.sciml.ai/ExponentialUtilities/stable/matrix_exponentials/#ExponentialUtilities.ExpMethodNative).

**Comment by ChrisRackauckas** [comment]
We should just change it to [ExpMethodGeneric](https://docs.sciml.ai/ExponentialUtilities/stable/matrix_exponentials/#ExponentialUtilities.ExpMethodGeneric) which should be faster. All of the methods solve to floating point accuracy so there shouldn't be a noticable difference to the user, though it should open up autodiff support and improve performance.
