### ISSUE TITLE
Type instability for ODEProblem?

### ISSUE THREAD

**Issue by NilsNiggemann** [SciML/OrdinaryDiffEq.jl#2024]
Maybe I am missing something, but `@code_warntype` reports a type instability when setting up an ODEProblem:

I am encountering this on Julia 1.9.3 with the newest version (OrdinaryDiffEq v6.55.0)

MWE:
from the tutorial:

```
using OrdinaryDiffEq
function lorenz!(du,u,p,t)
 du[1] = 10.0(u[2]-u[1])
 du[2] = u[1]*(28.0-u[3]) - u[2]
 du[3] = u[1]*u[2] - (8/3)*u[3]
end
u0 = [1.0;0.0;0.0]
tspan = (0.0,100.0)
```
Then I run @code_warntype:
```
julia> @code_warntype ODEProblem(lorenz!,u0,tspan)
MethodInstance for ODEProblem(::typeof(lorenz!), ::Vector{Float64}, ::Tuple{Float64, Float64})
  from ODEProblem(f, u0, tspan) @ SciMLBase /storage/user/.julia/packages/SciMLBase/DPrcG/src/problems/ode_problems.jl:174
Arguments
  #self#::Type{ODEProblem}
  f::Core.Const(lorenz!)
  u0::Vector{Float64}
  tspan::Tuple{Float64, Float64}
Body::Any
1 ─ %1 = SciMLBase.NullParameters()::Core.Const(SciMLBase.NullParameters())
│   %2 = (#self#)(f, u0, tspan, %1)::Any
└──      return %2

```

It looks like it cannot figure out the return type.

**Comment by avik-pal** [comment]
`ODEProblem(lorenz!,u0,tspan)` needs to do a runtime check to determine if the function is in place / out of place. If you use `ODEProblem{true}(lorenz!,u0,tspan)` then everything is inferred properly.

**Comment by NilsNiggemann** [comment]
Ah that makes sense,
Seems like I was overzealous when I was hunting type instabilities.
