### ISSUE TITLE
Rodas5P bug with continuous event

### ISSUE THREAD

**Issue by baggepinnen** [SciML/OrdinaryDiffEq.jl#2055]
In the following example, Rodas5P produces complete garbage, while many other solvers handle the problem just fine
```julia
using OrdinaryDiffEq, Plots
function f(du, u, p, t)
    du[1] = u[2]
    du[2] = -p
end
function condition(u, t, integrator) # Event when condition(u,t,integrator) == 0
    u[1]
end
function affect!(integrator)
    integrator.u[2] = -integrator.u[2]
end
cb = ContinuousCallback(condition, affect!)

u0 = [50.0, 0.0]
tspan = (0.0, 15.0)
p = 9.8
prob = ODEProblem(f, u0, tspan, p)
plot(
    plot(solve(prob, Tsit5(), callback = cb), title="Tsit5"),
    plot(solve(prob, Rodas4(), callback = cb), title="Rodas4"),
    plot(solve(prob, Rosenbrock23(), callback = cb), title="Rosenbrock23"),
    plot(solve(prob, Rodas5P(), callback = cb), title="Rodas5P"),
)
```
![image](https://github.com/SciML/OrdinaryDiffEq.jl/assets/3797491/a1216040-528d-4bcc-abfa-76102b7428ec)

Limiting `dtmax` for Rodas5P mitigates the problem

**Comment by baggepinnen** [comment]
Testing a few more
![image](https://github.com/SciML/OrdinaryDiffEq.jl/assets/3797491/cdad5bf2-67d8-4ccc-960f-b5fa27b6f871)

**Comment by baggepinnen** [comment]
Rodas5 and Rodas5P are both affected the same way. The saved points are good, but the interpolation appears off
```julia
prob = ODEProblem(f, big.(u0), big.(tspan), p)
sol = solve(prob, Rodas5P(), callback = cb, tstops=0.1)
plot(sol.t, Matrix(sol)', title="Rodas5P", m=:o, layout=2)
plot!(sol)
```
![image](https://github.com/SciML/OrdinaryDiffEq.jl/assets/3797491/fc781670-9281-4373-851e-6af07f17e6a0)

**Comment by gstein3m** [comment]
In function 

function _ode_addsteps!(k, t, uprev, u, dt, f, p, cache::Rosenbrock5ConstantCache,....

I found a bug which could be the reason: 

        copyat_or_push!(k, 1, k₁)
        copyat_or_push!(k, 2, k₂)
        copyat_or_push!(k, 2, k₃)

The last line should be
        copyat_or_push!(k, 3, k₃)

**Comment by ChrisRackauckas** [comment]
I was thinking it needs to be in the `addsteps!` part, but that dispatch is only for out of place dispatches? I created https://github.com/SciML/OrdinaryDiffEq.jl/pull/2057 which is a bit of clean-up, but the only immediate typo I see is that one (I also found `length(k) < 2` which could have a performance improvement)

**Comment by ChrisRackauckas** [comment]
@baggepinnen can you test the PR on that case?

**Comment by ChrisRackauckas** [comment]
oh, the interaction between https://github.com/SciML/OrdinaryDiffEq.jl/pull/2057/files#diff-8c298a1cd90d6f06977e222dc08c1a28a5be33c304cb2268d624aea307db98b1R911-R913 and `length(k) < 2` would do it, since then the interpolation would be correct in the event handling but the post-solution interpolation, which shouldn't be re-evaluating derivatives but would be with `length(k) < 2`, would change the k's.

**Comment by baggepinnen** [comment]
The PR #2057 did not solve the problem with the bouncing ball

![image](https://github.com/SciML/OrdinaryDiffEq.jl/assets/3797491/ce26ee9c-535d-48e6-a06b-29865ef505c9)

**Comment by gstein3m** [comment]
The error is in lines 663, 868 of stiff_add_steps.jl:

With 
`tmp = copy(k8) `
instead of 
`tmp = k8 `
it works.

**Comment by ChrisRackauckas** [comment]
Awesome, yeah it was an aliasing issue in the interpolation and David gave a nice way to do this without allocating, so https://github.com/SciML/OrdinaryDiffEq.jl/pull/2057 should handle this.
