### ISSUE TITLE
Improved traditional Rosenbrock–Wanner methods for stiff ODEs and DAEs by Joachim Rang

### ISSUE THREAD

**Issue by ranocha** [SciML/OrdinaryDiffEq.jl#2064]
See [Joachim Rang (2015) Improved traditional Rosenbrock–Wanner methods for stiff ODEs and DAEs](https://doi.org/10.1016/j.cam.2015.03.010)

**Comment by cwittens** [comment]
more information an additional methods can be found at https://leopard.tu-braunschweig.de/receive/dbbs_mods_00057194
