### ISSUE TITLE
Rosenbrock solvers fail or interpolate poorly due to (algebraically) inconsistent `u` after callback

### ISSUE THREAD

**Issue by topolarity** [SciML/OrdinaryDiffEq.jl#2127]
**Describe the bug 🐞**

Using a `DiscreteCallback` (specifically a PresetTimeCallback) with a DAE appears to be poorly behaved with a couple solvers.

**Expected behavior**

I expected each solver to solve from the discontinuity forward "as if" the simulation had been restarted.

**Minimal Reproducible Example**
```julia
julia> using OrdinaryDiffEq, DiffEqCallbacks, LinearAlgebra
julia> f(u, p, t) = [u[2], u[2] - p * sin(t)]
julia> mass_matrix = Diagonal([1.0,0.0])
julia> prob = ODEProblem(ODEFunction(f; mass_matrix), [0.0, 0.0], (0., 2π), 1,
                         callback=PresetTimeCallback(0:.3:2π, integ->(integ.p=-integ.p;)))

julia> sol = solve(prob, Rodas5P())
julia> plot(sol)

julia> sol = solve(prob, Rosenbrock23())
julia> plot(sol; xlim=(0, 2π))
```
**Rodas5P** has a bad interpolant for a couple timesteps after each discontinuity:
![image](https://github.com/SciML/OrdinaryDiffEq.jl/assets/84105208/010373c9-b51a-4b7a-90d5-dfa352eeb9bc)

**Rosenbrock23** fails to solve past `t = 0.3` (and **ROS34PRw** fails similarly):
![image](https://github.com/SciML/OrdinaryDiffEq.jl/assets/84105208/af80bf45-f66d-4401-8eae-c59e11520432)

**Comment by topolarity** [comment]
For reference, **FBDF** appears to solve this correctly:

![image](https://github.com/SciML/OrdinaryDiffEq.jl/assets/84105208/9d7069b2-6b99-4135-ae5b-80f794192bbf)

**Comment by ChrisRackauckas** [comment]
Only algebraic variables?

**Comment by topolarity** [comment]
As far as I've noticed, yeah - Only algebraic discontinuities are an issue

**Comment by topolarity** [comment]
IDA also appears to struggle to get past the first stop:
```julia
julia> using OrdinaryDiffEq, DiffEqCallbacks, Sundials
julia> f(du, u, p, t) = [du[1] - u[2], u[2] - p * sin(t)]
julia> prob = DAEProblem(DAEFunction(f), [0.0, 0.0], [0.0, 0.0], (0., 2π), 1,
                         callback=PresetTimeCallback(0:.3:2π, integ->(integ.p=-integ.p;)),
                         differential_vars=[true,false])
julia> sol = solve(prob, IDA())
julia> plot(sol; xlim=(0, 2π))
```
![image](https://github.com/SciML/OrdinaryDiffEq.jl/assets/84105208/330b84bc-c43d-4e7b-9ffb-d2d85904aeaf)

**Comment by ChrisRackauckas** [comment]
Is this all on latest?

**Comment by gstein3m** [comment]
Rosenbrock methods require consistent initial values for DAEs, i.e. algebraic equations should be fulfilled.
If you induce discontinuities in the algebraic equations, the current solution is no longer consistent.
Therefore, the integrator will usually abort or the interpolation is no longer correct.
The following modification should solve the problem:
```
function affect!(integrator) 
    integrator.p = -integrator.p
    integrator.u[2] = -integrator.u[2]
end

prob = ODEProblem(ODEFunction(f; mass_matrix), [0.0, 0.0], (0., 2π), 1,
                               callback=PresetTimeCallback(0:.3:2π, affect!))

```

**Comment by topolarity** [comment]
Yeah, the problem is certainly that `u` is inconsistent after the discontinuity, although I'm not so sure that it should the responsibility of the callback to find a consistent starting condition (especially since it can require a non-linear solve in general).

To take the analogy with initialization (where we have the same problem):
```julia
julia> prob = ODEProblem(ODEFunction(f; mass_matrix), [0.0, 100.0], (0., 2π), 1) # provide inconsistent u0[2]
julia> sol = solve(prob, Rosenbrock23())
retcode: Success
Interpolation: specialized 2nd order "free" stiffness-aware interpolation
t: 12834-element Vector{Float64}:
 0.0
 1.0e-6
 ⋮
 6.283185307179586
u: 12834-element Vector{Vector{Float64}}:
 [0.0, 0.0]
 [4.999999999999791e-13, 9.999999999999288e-7]
 ⋮
 [-3.633302206017213e-11, -2.442385622089885e-16]
```

The inconsistent conditions are resolved automatically by the solve routine.

**Comment by ChrisRackauckas** [comment]
We should do a reinitialization after `u_modified!` on callbacks. We do it on DAEs but I don't think we do it on the mass matrix ODEs right now.

**Comment by oscardssmith** [comment]
I think this might also explain some of the weird behavior I've seen with FBDF timestepping after discontinuities.

**Comment by topolarity** [comment]
Do we know why IDA fails to solve? Is it also missing a reinit?

**Comment by ChrisRackauckas** [comment]
IDA has a reinitialization. It must not be reinitializable with your choice of initialize. Brown basic?
