### ISSUE TITLE
New Runge–Kutta pairs of orders 9(8) for use in quadruple precision computations

### ISSUE THREAD

**Issue by ranocha** [SciML/OrdinaryDiffEq.jl#2159]
Kovalnogov VN, Fedorov RV, Karpukhina TV, Simos TE, Tsitouras C. Runge–Kutta pairs of orders 9 (8) for use in quadruple precision computations. Numerical Algorithms. 2023 Aug 24:1-5.

https://doi.org/10.1007/s11075-023-01632-8

**Comment by cwittens** [comment]
shouldn't this issue be closed now that https://github.com/SciML/OrdinaryDiffEq.jl/pull/2166 is merged?
