### ISSUE TITLE
Some methods are in the wrong sub-package

### ISSUE THREAD

**Issue by ranocha** [SciML/OrdinaryDiffEq.jl#2373]
1. `SHLDDRK_2N` and `SHLDDRK52` should be moved from OrdinaryDiffEqSSPRK.jl to OrdinaryDiffEqLowStorageRK.jl since they are not SSP
2. `KYK2014DGSSPRK_3S2` should be moved from OrdinaryDiffEqLowStorageRK.jl to OrdinaryDiffEqSSPRK.jl since the other SSP methods are there, even if they are low storage (which most of them are)
3. The docstring of `ssp_coefficient` should move from OrdinaryDiffEqLowStorageRK.jl to OrdinaryDiffEqSSPRK.jl or OrdinaryDiffEqCore.jl

### Details

https://github.com/SciML/OrdinaryDiffEq.jl/blob/dc0e1e733fdd79a6c643cbd0c4f4be03c934cb91/lib/OrdinaryDiffEqSSPRK/src/OrdinaryDiffEqSSPRK.jl#L102

`SHLDDRK_2N` and `SHLDDRK52` are not SSP methods but low-storage methods. There is also no `ssp_coefficient` defined for them, see 

https://github.com/SciML/OrdinaryDiffEq.jl/blob/dc0e1e733fdd79a6c643cbd0c4f4be03c934cb91/lib/OrdinaryDiffEqSSPRK/src/alg_utils.jl#L36-L52

https://github.com/SciML/OrdinaryDiffEq.jl/blob/dc0e1e733fdd79a6c643cbd0c4f4be03c934cb91/lib/OrdinaryDiffEqLowStorageRK/src/OrdinaryDiffEqLowStorageRK.jl#L107

`KYK2014DGSSPRK_3S2` is an SSP method, see also

https://github.com/SciML/OrdinaryDiffEq.jl/blob/dc0e1e733fdd79a6c643cbd0c4f4be03c934cb91/lib/OrdinaryDiffEqLowStorageRK/src/alg_utils.jl#L86-L100

**Comment by ChrisRackauckas** [comment]
@ParamThakkar123 can you take a look at this?

**Comment by ParamThakkar123** [comment]
Yes I will take this. I will make the change

**Comment by ranocha** [comment]
Thanks!

**Comment by ParamThakkar123** [comment]
@ranocha the fix has been incorporated in my recent PR #2320

**Comment by oscardssmith** [comment]
IMO it relaly should be a separate PR to make review easier (especially because I expect this change to merge sooner).

**Comment by ChrisRackauckas** [comment]
Did these fixes get a separate PR?

**Comment by ParamThakkar123** [comment]
> Did these fixes get a separate PR?

Actually I first did this in the same PR #2320. But then on @oscardssmith suggestion, I reverted it and will start a new one soon.

**Comment by ParamThakkar123** [comment]
@ranocha should the cache also be modified like in `SHLDDRK_2N` uses `SSPRKMutableCache` 

like here : 
![Uploading image.png…]()

**Comment by ChrisRackauckas** [comment]
yes fix the abstract types.

**Comment by ParamThakkar123** [comment]
> yes fix the abstract types.

Should I replace SSPRKMutableCache directly to LowStorageRKCache ?? Or there would be some other changes to make

**Comment by ChrisRackauckas** [comment]
Both subpackages have an abstract type for the caches of their group. Just apply the one for the destination.
