### ISSUE TITLE
Stuck when precompiling OrdinaryDiffEqDefault

### ISSUE THREAD

**Issue by jgsimard** [SciML/OrdinaryDiffEq.jl#2432]
I updated all packages using the update command. Now the precomilation is stuck on OrdinaryDiffEqDefault. I tried on two different computer and the same thing happened

**Comment by ChrisRackauckas** [comment]
How long did you wait? More than an hour?

**Comment by ChrisRackauckas** [comment]
What version of Julia?

**Comment by jgsimard** [comment]
I waited all night. version 10.3

**Comment by ChrisRackauckas** [comment]
10.3 has a bug in the GC. Try 10.4?

**Comment by martincornejo** [comment]
Updating to Julia 1.10.4 solved this for me

**Comment by ChrisRackauckas** [comment]
Okay yeah, that is known. Julia had the v1.10.4 release because this bug was found in Julia with this library. So it's pretty required.

**Comment by jgsimard** [comment]
thanks!
