### ISSUE TITLE
Type instability interpolating solution from out of place prob with default solver

### ISSUE THREAD

**Issue by densmojd** [SciML/OrdinaryDiffEq.jl#2530]
Interpolating a solution from a non-mutating problem definition is type unstable, but using a mutating definition is fine.

MWE:

```
using OrdinaryDiffEq

function f1(du, u, p, t)
       du .= -u
end

function f2(u, p, t)
       -u
end

sol1 = solve(ODEProblem(f1, [1.0, 2.0, 3.0], (0.0, 10.0)))
sol2 = solve(ODEProblem(f2, [1.0, 2.0, 3.0], (0.0, 10.0)))

@code_warntype sol1(1.0) # type stable
@code_warntype sol2(1.0) # type unstable

```
I'm using Julia 1.11.1 and OrdinaryDiffEq.jl v6.90.1

**Comment by oscardssmith** [comment]
looks like a bug with the default solver.

**Comment by oscardssmith** [comment]
specifically, we seem to be creating the cache with an abstract type incorrectly...

```
