### ISSUE TITLE
DelayDiffEq Integration Tests are not using dev version of OrdinaryDiffEqCore, etc.

### ISSUE THREAD

**Issue by jClugstor** [SciML/OrdinaryDiffEq.jl#2553]
**Describe the bug 🐞**

The DelayDiffEq integration tests are using the registered versions of 
OrdinaryDiffEqCore
OrdinaryDiffEqNonlinearSolve
OrdinaryDiffEqDifferentiation
OrdinaryDiffEqDefault
OrdinaryDiffEqRosenbrock

**Expected behavior**

I think these should be the dev versions, just like all the other subpackages in /lib.

**Minimal Reproducible Example 👇**
You can see this issue in the github actions, in the run downstream tests portion: https://github.com/SciML/OrdinaryDiffEq.jl/actions/runs/12172093082/job/33950156892
and to make sure it's not from my PR, it's also happening on main: https://github.com/SciML/OrdinaryDiffEq.jl/actions/runs/12182367599/job/33981209793.

**Additional context**

The packages are being developed in the "Develop the libraries..." section, but the dev versions aren't being used for the tests for some reason.

**Comment by oscardssmith** [comment]
@avik-pal this is the issue @ChrisRackauckas said I should ask you about.

**Comment by avik-pal** [comment]
There are 2 solutions:

1. https://github.com/SciML/NonlinearSolve.jl/blob/master/.github/workflows/CI_NonlinearSolve.yml manually installs the sub-packages.
2. The nicer way would be to specify `[sources]` like Lux does https://github.com/LuxDL/Lux.jl/blob/main/Project.toml#L115. Note this only works on 1.11+

**Comment by jClugstor** [comment]
It does manually install the subpackages, in pretty much the same way that NonlinearSolve does for it's downstream tests, https://github.com/SciML/NonlinearSolve.jl/blob/master/.github/workflows/Downstream.yml, https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/.github/workflows/Downstream.yml. If you compare the two they're practically the same, but only OrdinaryDiffEq has the issue. 

I think what's happening is that when OrdindaryDiffEq is dev'ed in the line
`Pkg.develop(PackageSpec(path="."))` it installs OrdinaryDiffEqCore, OrdinaryDiffEqNonlinearSolve, OrdinaryDiffEqDifferentiation, OrdinaryDiffEqDefault and OrdinaryDiffEqRosenbrock from the registry. 

But I'm also not sure I understand what's happening in the Downstream tests in the first place. It looks like the project "." is activated, then the packages are dev'ed. Then another project, "downstream" is activated, OrdinaryDiffEq is dev'ed, and then the tests are ran. I'm not sure how the right packages are being dev'ed in the "downstream" project in the first place, but at least most of them are.
