### ISSUE TITLE
Control problem example

### ISSUE THREAD

**Issue by moesphere** [SciML/OrdinaryDiffEq.jl#340]
I've done a Pkg.update() and copied the code of the control example (see [here](http://docs.juliadiffeq.org/latest/features/diffeq_arrays.html#Example:-A-Control-Problem-1)) into my editor. 
However, the solve line returns an error stating "no method matching condition(...)". Apparently only three arguments are handed over, but four are needed.

**Comment by moesphere** [comment]
Removing 'p' from the condition functions work, as there are no parameters in the differential equations.

**Comment by ChrisRackauckas** [comment]
Yes, the `p`s shouldn't be there. That's a docs error.
