### ISSUE TITLE
Fix interpolation printing for composites

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/OrdinaryDiffEq.jl#440]
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/interp_func.jl#L66-L68

That default makes it say that composite algorithms are 3rd order Hermite instead of listing the two interpolations. It should instead just print out both.

**Comment by ordicker** [comment]
I think you can close this issue. [merged pull request](https://github.com/SciML/OrdinaryDiffEq.jl/pull/1504#issue-1028386947)
