### ISSUE TITLE
Gitlab Runner doesn't run for PRs from forks

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/OrdinaryDiffEq.jl#832]
https://github.com/JuliaDiffEq/SparseDiffTools.jl/blob/master/src/differentiation/compute_jacobian_ad.jl#L88

**Comment by devmotion** [comment]
https://github.com/JuliaGPU/gitlab-ci#pull-requests-from-forks shows a way to circumvent the limitations of Gitlab CI.
